import 'a2jauthor/src/debug-panel/debug-panel-test'
import 'a2jauthor/src/interviews/interviews-test'
import 'a2jauthor/src/loading/loading-test'
import 'a2jauthor/src/about/about-test'
import 'a2jauthor/src/about/authors/authors-test'
import 'a2jauthor/src/about/feedback/feedback-test'
import 'a2jauthor/src/about/layout/layout-test'
// import 'a2jauthor/src/about/main/main-test'
import 'a2jauthor/src/about/revision/revision-test'
// import 'a2jauthor/src/mapper/mapper-test'
// import 'a2jauthor/src/mapper/mapper-list/mapper-list-test'
// import 'a2jauthor/src/mapper/mapper-canvas/mapper-canvas-test'
import 'a2jauthor/src/models/tests/models-test'
import 'a2jauthor/src/popover/popover-test'
import 'a2jauthor/src/report/report-test'
import 'a2jauthor/legacy/a2j-legacy-tests'
import 'a2jauthor/src/utils/tests/'
import 'a2jauthor/src/vertical-navbar/vertical-navbar-test'
// import 'a2jauthor/src/templates/templates-test'
// import 'a2jauthor/src/templates/edit/edit-test'
// import 'a2jauthor/src/templates/edit/toolbar/toolbar-test'
// import 'a2jauthor/src/templates/list/item/item-test'
// import 'a2jauthor/src/templates/list/sortbar/sortbar-test'
