import 'a2jauthor/models/fixtures/'
import 'a2jauthor/models/tests/guide-test'
import 'a2jauthor/models/tests/app-state-test'
import 'a2jauthor/utils/move-item-array-test'
import 'a2jauthor/popover/popover-test'
import 'a2jauthor/report/report-test'
import 'a2jauthor/interviews/interviews-test'
import 'a2jauthor/loading/loading-test'
import 'a2jauthor/vertical-navbar/vertical-navbar-test'
import 'a2jauthor/debug-panel/debug-panel-test'
import 'a2jauthor/src/a2j-legacy-tests'
import 'a2jauthor/mapper/mapper-test'
import 'a2jauthor/mapper/mapper-list/mapper-list-test'
import 'a2jauthor/mapper/mapper-canvas/mapper-canvas-test'
// import 'a2jauthor/templates/templates-test'
// import 'a2jauthor/templates/edit/edit-test'
// import 'a2jauthor/templates/edit/toolbar/toolbar-test'
// import 'a2jauthor/templates/list/item/item-test'
// import 'a2jauthor/templates/list/sortbar/sortbar-test'
