/*
2015-07-06

SQLyog Enterprise - MySQL GUI v5.17
Host - 5.0.95 : Database - caja_dev
*********************************************************************
Server version : 5.0.95
*/

SET NAMES utf8;

SET SQL_MODE='';

create database if not exists `caja_dev`;

USE `caja_dev`;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO';


/*Table structure for table `users` */

CREATE TABLE `users` (
  `uid` int(11) default NULL,
  `username` varchar(64) NOT NULL,
  `nickname` varchar(64) default NULL,
  `folder` varchar(64) default NULL,
  `notes` varchar(30) default NULL,
  `pkuid` int(11) NOT NULL auto_increment,
  PRIMARY KEY  (`pkuid`),
  UNIQUE KEY `uid` (`uid`)
) ENGINE=MyISAM AUTO_INCREMENT=35 DEFAULT CHARSET=latin1;

/*Data for the table `users` */

insert into `users` (`uid`,`username`,`nickname`,`folder`,`notes`,`pkuid`) values (0,'admin','admin','admin','reserved',1);
insert into `users` (`uid`,`username`,`nickname`,`folder`,`notes`,`pkuid`) values (26,'demo','Demo User','demo','demo to run',5);
insert into `users` (`uid`,`username`,`nickname`,`folder`,`notes`,`pkuid`) values (1,'a2j','A2J Staff','A2J','owner of A2J samples',6);
insert into `users` (`uid`,`username`,`nickname`,`folder`,`notes`,`pkuid`) values (45,'dev','Author Developer','dev','sam\'s CAJA developer',7);
insert into `users` (`uid`,`username`,`nickname`,`folder`,`notes`,`pkuid`) values (12,'sam','Sam Goshorn','sam',NULL,9);
insert into `users` (`uid`,`username`,`nickname`,`folder`,`notes`,`pkuid`) values (9,'jmayer','John Mayer','jmayer',NULL,10);
insert into `users` (`uid`,`username`,`nickname`,`folder`,`notes`,`pkuid`) values (8,'emasters','Elmer Masters','emasters',NULL,11);
insert into `users` (`uid`,`username`,`nickname`,`folder`,`notes`,`pkuid`) values (47,'a2jtester','Test Tester','a2jtester',NULL,13);
insert into `users` (`uid`,`username`,`nickname`,`folder`,`notes`,`pkuid`) values (46,'LSC Demo','LSC DEMO','LSC Demo',NULL,14);
insert into `users` (`uid`,`username`,`nickname`,`folder`,`notes`,`pkuid`) values (11,'Jessica Frank','Jessica Bolack Frank','Jessica Frank',NULL,15);
insert into `users` (`uid`,`username`,`nickname`,`folder`,`notes`,`pkuid`) values (116,'arabanal','Alex Rabanal','arabanal',NULL,34);


/*Table structure for table `guides` */

CREATE TABLE `guides` (
  `editoruid` bigint(20) default NULL,
  `isPublic` tinyint(1) default NULL,
  `isFree` tinyint(1) default NULL,
  `gid` bigint(20) NOT NULL auto_increment,
  `filename` varchar(200) default NULL,
  `title` varchar(200) default NULL,
  `created` timestamp NOT NULL default CURRENT_TIMESTAMP,
  `CALIcode` varchar(20) default NULL,
  `CALIowned` tinyint(1) default NULL,
  `clonedfromgid` bigint(20) default NULL,
  `owner` varchar(20) default NULL,
  `notes` text,
  `alias` varchar(200) default NULL,
  `CALIid` bigint(20) default NULL,
  `archive` tinyint(1) unsigned zerofill NOT NULL,
  PRIMARY KEY  (`gid`),
  UNIQUE KEY `filename` (`filename`),
  KEY `created` (`created`),
  KEY `title` (`title`)
) ENGINE=MyISAM AUTO_INCREMENT=600 DEFAULT CHARSET=utf8;

/*Data for the table `guides` */

insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (0,0,0,1,'nothing.xml','Test 1','2012-10-05 00:00:00','',1,0,NULL,'First entry for testing',NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,0,0,3,'dev/guides/CAPageTypes/CBK_CAPAGETYPES_jqBookData.xml','CALI Author Page Types','2012-10-05 00:00:00','CAJA_CAPAGETYPES',0,0,NULL,'CALI Author Page Type Test Lesson',NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (1,1,1,5,'A2J/guides/A2J_MobileOnline/A2J_MobileOnlineInterview_Interview.xml','A2J Mobile Online Interview','2012-10-05 00:00:00',NULL,0,0,NULL,'A2J Real Mobile Interview',NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (-1,0,0,111,'CCALI/guides/BA/BA08/BA08.xml','CALI Author - Are You My Partner? Is This a Partnership?','2012-10-12 15:01:22','BA08',1,0,'2','CALI Lesson','http://www.cali.org/lessons/web/ba08/',373,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (-1,0,0,119,'CCALI/guides/EVD/EVD04/EVD04.xml','Character Evidence Under Federal Rules','2012-10-12 15:01:22','EVD04',1,0,'2','CALI Lesson','http://www.cali.org/lessons/web/evd04/',528,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (-1,0,0,131,'CCALI/guides/EVD/EVD16/EVD16.xml','An Overview of Relevance and Hearsay: A Nine Step Analytical Guide','2012-10-12 15:01:22','EVD16',1,0,'2','CALI Lesson','http://www.cali.org/lessons/web/evd16/',1057,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (-1,0,0,132,'demo/guides/EVD03/EVD03.xml','CALI Author - Survey of Evidence','2014-08-28 13:33:19',NULL,NULL,118,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (26,0,0,133,'demo/guides/A2J_MobileOnline/A2J_MobileOnlineInterview_Interview.xml','Demo Mobile Volunteer Lawyers Program online interview','2014-08-28 13:33:19',NULL,NULL,5,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (1,1,1,134,'A2J/guides/A2J_NYSample/A2J_NYSample_Interview.xml','NYS Surrogate\'s Small Estate Settlement','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (1,1,1,135,'A2J/guides/A2J_ULSOnlineIntake081611/A2J_ULSOnlineIntake081611_Interview.xml','Utah Legal Services Online Intake','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (12,0,0,136,'demo/guides/CharTest/Field Characters Test.a2j','Interview Title: Field Characters Test (Eç§á»Ð´Ã© - <\\\'&\\\">)','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (8,NULL,NULL,177,'emasters/guides/Guide177/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (12,NULL,NULL,178,'sam/guides/Guide178/Guide.xml','My super Cool Interview','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (9,NULL,NULL,179,'jmayer/guides/Guide179/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (9,NULL,NULL,180,'jmayer/guides/Guide180/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (8,NULL,NULL,182,'emasters/guides/Guide182/Guide.xml','My Sample Guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (26,0,0,183,'demo/guides/A2J_ULSOnlineIntake/A2J_ULSOnlineIntake081611_Interview.xml','Demo Utah Legal Services Online Intake','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (26,0,0,184,'demo/guides/A2J_NYSample/A2J_NYSample_interview.xml','Demo NYS Surrogate\\\'s Small Estate Settlement','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (26,NULL,NULL,235,'demo/guides/Guide235/Guide.xml','Sam\'s Guide to Guiding Guides','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (26,NULL,NULL,236,'demo/guides/Guide236/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (26,NULL,NULL,237,'demo/guides/Guide237/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,238,'dev/guides/Guide238/Guide.xml','test 2','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (26,NULL,NULL,239,'demo/guides/Guide239/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (26,NULL,NULL,240,'demo/guides/Guide240/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,0,0,252,'dev/guides/A2JFieldTypes/A2J_FieldTypesTest_Interview.xml','Labor Day! LOCALHOST - CURRENT Test Field Types test 252','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (47,NULL,NULL,253,'a2jtester/guides/Guide253/Guide.xml','Tester For My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (46,NULL,NULL,254,'LSC Demo/guides/Guide254/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (47,NULL,NULL,255,'a2jtester/guides/Guide255/Guide.xml','This is my second guide.','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (9,NULL,NULL,310,'jmayer/guides/Guide310/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,317,'Jessica Frank/guides/Guide317/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,318,'Jessica Frank/guides/Guide318/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,319,'Jessica Frank/guides/Guide319/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,320,'Jessica Frank/guides/Guide320/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,322,'dev/guides/Guide322/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,323,'dev/guides/Guide323/Guide.xml','My guide test','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,324,'dev/guides/Guide324/Guide.xml','\\\"<&>\\\'  My <b>Interview</b>','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,325,'dev/guides/Guide325/Guide.xml','Calculator Test For A2J5 (DEV)','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,326,'dev/guides/Guide326/Guide.xml','Test Field Types','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,327,'dev/guides/Guide327/Guide.xml','Test Field Types','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,328,'dev/guides/Guide328/Guide.xml','Test Field Types MAIN','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,329,'Jessica Frank/guides/Guide329/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,330,'Jessica Frank/guides/Guide330/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,331,'Jessica Frank/guides/Guide331/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,332,'Jessica Frank/guides/Guide332/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,333,'Jessica Frank/guides/Guide333/Guide.xml','Sample A2J Guided Interview ','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,334,'dev/guides/Guide334/Guide.xml','TestLocal - Calculator Test File #2 2015-01-21 <<\\\"&\\\'>>','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,335,'dev/guides/Guide335/Guide.xml','Sam\\\'s 2012 = Test Field Types 2012-03-29','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,336,'Jessica Frank/guides/Guide336/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,337,'Jessica Frank/guides/Guide337/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,338,'Jessica Frank/guides/Guide338/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,339,'dev/guides/Guide339/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,340,'dev/guides/Guide340/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,341,'Jessica Frank/guides/Guide341/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,342,'Jessica Frank/guides/Guide342/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,343,'Jessica Frank/guides/Guide343/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,344,'Jessica Frank/guides/Guide344/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (49,NULL,NULL,345,'draymer/guides/Guide345/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,346,'Jessica Frank/guides/Guide346/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,347,'Jessica Frank/guides/Guide347/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,348,'dev/guides/Guide348/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,349,'Jessica Frank/guides/Guide349/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,350,'Jessica Frank/guides/Guide350/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,351,'Jessica Frank/guides/Guide351/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,352,'Jessica Frank/guides/Guide352/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,353,'Jessica Frank/guides/Guide353/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,354,'Jessica Frank/guides/Guide354/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (79,NULL,NULL,355,'dnikitaides/guides/Guide355/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (83,NULL,NULL,356,'craige/guides/Guide356/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (83,NULL,NULL,357,'craige/guides/Guide357/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (83,NULL,NULL,358,'craige/guides/Guide358/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (83,NULL,NULL,359,'craige/guides/Guide359/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (83,NULL,NULL,360,'craige/guides/Guide360/Guide.xml','My guide 2','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (85,NULL,NULL,361,'northcomllc/guides/Guide361/Guide.xml','Nested Repeat Demo','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (10,NULL,NULL,362,'amedeiro/guides/Guide362/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (9,NULL,NULL,363,'jmayer/guides/Guide363/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,364,'Jessica Frank/guides/Guide364/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (82,NULL,NULL,365,'skim/guides/Guide365/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,366,'Jessica Frank/guides/Guide366/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,367,'Jessica Frank/guides/Guide367/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,368,'Jessica Frank/guides/Guide368/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,369,'Jessica Frank/guides/Guide369/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (79,NULL,NULL,370,'dnikitaides/guides/Guide370/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (110,NULL,NULL,371,'hkaufman/guides/Guide371/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (79,NULL,NULL,372,'dnikitaides/guides/Guide372/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (79,NULL,NULL,373,'dnikitaides/guides/Guide373/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (79,NULL,NULL,374,'dnikitaides/guides/Guide374/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (79,NULL,NULL,375,'dnikitaides/guides/Guide375/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (79,NULL,NULL,376,'dnikitaides/guides/Guide376/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,377,'Jessica Frank/guides/Guide377/Guide.xml','Repeat Loop Examples','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (114,NULL,NULL,378,'croussea/guides/Guide378/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (49,NULL,NULL,379,'draymer/guides/Guide379/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (109,NULL,NULL,380,'sbarnes2/guides/Guide380/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (114,NULL,NULL,381,'croussea/guides/Guide381/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (112,NULL,NULL,382,'mobiala/guides/Guide382/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,383,'Jessica Frank/guides/Guide383/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (9,NULL,NULL,384,'jmayer/guides/Guide384/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (111,NULL,NULL,385,'amay1/guides/Guide385/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (114,NULL,NULL,386,'croussea/guides/Guide386/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (113,NULL,NULL,387,'rrosenbl/guides/Guide387/Guide.xml','Declaration Regarding Child Support Factors--FL014','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (112,NULL,NULL,388,'mobiala/guides/Guide388/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (109,NULL,NULL,389,'sbarnes2/guides/Guide389/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (110,NULL,NULL,390,'hkaufman/guides/Guide390/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (9,NULL,NULL,391,'jmayer/guides/Guide391/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (49,NULL,NULL,392,'draymer/guides/Guide392/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (114,NULL,NULL,393,'croussea/guides/Guide393/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (110,NULL,NULL,394,'hkaufman/guides/Guide394/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (114,NULL,NULL,395,'croussea/guides/Guide395/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (49,NULL,NULL,396,'draymer/guides/Guide396/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (9,NULL,NULL,397,'jmayer/guides/Guide397/Guide.xml','Sample Health Care Power of Attorney','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (49,NULL,NULL,398,'draymer/guides/Guide398/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (114,NULL,NULL,399,'croussea/guides/Guide399/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (110,NULL,NULL,400,'hkaufman/guides/Guide400/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (49,NULL,NULL,401,'draymer/guides/Guide401/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (113,NULL,NULL,402,'rrosenbl/guides/Guide402/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,403,'Jessica Frank/guides/Guide403/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (114,NULL,NULL,404,'croussea/guides/Guide404/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (114,NULL,NULL,405,'croussea/guides/Guide405/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (112,NULL,NULL,406,'mobiala/guides/Guide406/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (112,NULL,NULL,407,'mobiala/guides/Guide407/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (110,NULL,NULL,408,'hkaufman/guides/Guide408/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (114,NULL,NULL,409,'croussea/guides/Guide409/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (109,NULL,NULL,410,'sbarnes2/guides/Guide410/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (112,NULL,NULL,411,'mobiala/guides/Guide411/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (49,NULL,NULL,412,'draymer/guides/Guide412/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (111,NULL,NULL,413,'amay1/guides/Guide413/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (111,NULL,NULL,414,'amay1/guides/Guide414/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (109,NULL,NULL,415,'sbarnes2/guides/Guide415/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,416,'Jessica Frank/guides/Guide416/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,417,'Jessica Frank/guides/Guide417/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (9,NULL,NULL,418,'jmayer/guides/Guide418/Guide.xml','Sample Health Care Power of Attorney','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (9,NULL,NULL,419,'jmayer/guides/Guide419/Guide.xml','Sample Health Care Power of Attorney','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (49,NULL,NULL,420,'draymer/guides/Guide420/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (84,NULL,NULL,421,'crobinson/guides/Guide421/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,422,'Jessica Frank/guides/Guide422/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (83,NULL,NULL,423,'craige/guides/Guide423/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (83,NULL,NULL,424,'craige/guides/Guide424/Guide.xml','Untitled','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,425,'Jessica Frank/guides/Guide425/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (9,NULL,NULL,426,'jmayer/guides/Guide426/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,427,'dev/guides/Guide427/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (115,NULL,NULL,428,'dan/guides/Guide428/Guide.xml','The Blank Guide on authordev of Dan Nagy','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,429,'dev/guides/Guide429/Guide.xml','LOCALHOST - Test Field Types','2014-08-28 13:33:19',NULL,NULL,252,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,445,'dev/guides/Guide445/Guide.xml','TestLocal - Test Field Types','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,446,'dev/guides/Guide446/Guide.xml','NYS Surrogate\\\'s Small Estate Settlement','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,447,'dev/guides/Guide447/Guide.xml','TestLocal - Test Field Types','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,448,'dev/guides/Guide448/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,449,'dev/guides/Guide449/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (9,NULL,NULL,450,'jmayer/guides/Guide450/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,451,'dev/guides/Guide451/Guide.xml','Mobile Volunteer Lawyers Program online interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (9,NULL,NULL,452,'jmayer/guides/Guide452/Guide.xml','NYS Surrogate\\\'s Small Estate Settlement','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,453,'dev/guides/Guide453/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,454,'Jessica Frank/guides/Guide454/Guide.xml','My beta testing Guided Interview for authordev-- Use for testing! ','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,455,'Jessica Frank/guides/Guide455/Guide.xml','My beta testing Guided Interview for authordev','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,456,'Jessica Frank/guides/Guide456/Guide.xml','A2J with all question type variables','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (9,NULL,NULL,457,'jmayer/guides/Guide457/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,458,'Jessica Frank/guides/Guide458/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,459,'Jessica Frank/guides/Guide459/Guide.xml','U of Miami Pre-Need Guardianship form for testing logic','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,460,'Jessica Frank/guides/Guide460/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,461,'Jessica Frank/guides/Guide461/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,462,'dev/guides/Guide462/Guide.xml','TestLocal - Loop Repeat Variables Without Scripts','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,463,'dev/guides/Guide463/Guide.xml','Test Changes for 4.0.2','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,464,'dev/guides/Guide464/Guide.xml','OLD Repeat Variable Test 2014-06-27','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,465,'Jessica Frank/guides/Guide465/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,466,'dev/guides/Guide466/Guide.xml','HRC Final (SJG)','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,467,'dev/guides/Guide467/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,468,'dev/guides/Guide468/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,469,'Jessica Frank/guides/Guide469/Guide.xml','Nested Repeat Loops','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,470,'Jessica Frank/guides/Guide470/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,471,'dev/guides/Guide471/Guide.xml','My guide 2 for LABOR DAY','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (9,NULL,NULL,472,'jmayer/guides/Guide472/Guide.xml','READABILITY OF THE LAW','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,473,'Jessica Frank/guides/Guide473/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,474,'dev/guides/Guide474/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,475,'dev/guides/Guide475/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,476,'dev/guides/Guide476/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,477,'dev/guides/Guide477/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,478,'dev/guides/Guide478/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,479,'dev/guides/Guide479/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,480,'dev/guides/Guide480/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,481,'dev/guides/Guide481/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,482,'dev/guides/Guide482/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,483,'dev/guides/Guide483/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,484,'dev/guides/Guide484/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,485,'dev/guides/Guide485/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,486,'dev/guides/Guide486/Guide.xml','My guide','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,487,'dev/guides/Guide487/Guide.xml','','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,488,'dev/guides/Guide488/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,489,'Jessica Frank/guides/Guide489/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,490,'dev/guides/Guide490/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,491,'Jessica Frank/guides/Guide491/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,492,'dev/guides/Guide492/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,493,'Jessica Frank/guides/Guide493/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,494,'dev/guides/Guide494/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,495,'dev/guides/Guide495/Guide.xml','Mobile Volunteer Lawyers Program online interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,496,'dev/guides/Guide496/Guide.xml','Test Field Types 2014-07-29','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,497,'dev/guides/Guide497/Guide.xml','Logic Script Tester','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,498,'dev/guides/Guide498/Guide.xml','Test Field Types 2014-07-29','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,499,'dev/guides/Guide499/Guide.xml','Test Field Types 2014-07-29','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,500,'dev/guides/Guide500/Guide.xml','Test Field Types 2014-08-01','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,501,'dev/guides/Guide501/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,502,'dev/guides/Guide502/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,503,'dev/guides/Guide503/Guide.xml','Untitled uploaded guide','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,504,'dev/guides/Guide504/Guide.xml','California Declaration in Support of Modification of Child Support','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,505,'dev/guides/Guide505/Guide.xml','Untitled uploaded guide','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,506,'dev/guides/Guide506/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,507,'dev/guides/Guide507/Guide.xml','Capacity Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,508,'dev/guides/Guide508/Guide.xml','Capacity Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,509,'dev/guides/Guide509/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,510,'dev/guides/Guide510/Guide.xml','My Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,511,'dev/guides/Guide511/Guide.xml','Untitled uploaded guide','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,512,'dev/guides/Guide512/Guide.xml','Capacity Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,513,'dev/guides/Guide513/Guide.xml','Capacity Interview Auto UTF8','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,514,'dev/guides/Guide514/Guide.xml','Capacity Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,515,'dev/guides/Guide515/Guide.xml','Capacity Interview','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,516,'dev/guides/Guide516/Guide.xml','Untitled uploaded guide','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,517,'dev/guides/Guide517/Guide.xml','Pre-semester survey','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,518,'Jessica Frank/guides/Guide518/Guide.xml','Untitled uploaded guide','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,519,'Jessica Frank/guides/Guide519/Guide.xml','California Declaration in Support of Modification of Child Support','2014-08-28 13:33:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,520,'dev/guides/Guide520/Guide.xml','TestLocal - Steps','2014-08-28 13:33:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (NULL,NULL,NULL,521,NULL,'blah','2014-08-28 13:32:06',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,522,'Jessica Frank/guides/Guide522/Guide.xml','My Interview','2014-08-29 13:53:32',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,523,'Jessica Frank/guides/Guide523/Guide.xml','My Interview','2014-08-29 14:05:08',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,524,'Jessica Frank/guides/Guide524/Guide.xml','Sample uploading GI ','2014-08-29 14:09:34',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,525,'dev/guides/Guide525/Guide.xml','TestLocal - Media','2014-08-29 14:12:12',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,526,'dev/guides/Guide526/Guide.xml','My Interview','2014-08-29 14:21:17',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,527,'dev/guides/Guide527/Guide.xml','My Interview','2014-08-29 14:29:48',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,528,'dev/guides/Guide528/Guide.xml','My Interview','2014-08-29 14:31:52',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,529,'dev/guides/Guide529/Guide.xml','TestLocal Max Length','2014-08-29 14:32:51',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,530,'dev/guides/Guide530/Guide.xml','My Interview','2014-08-29 14:36:48',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,531,'dev/guides/Guide531/Guide.xml','My Interview','2014-08-29 14:47:49',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,532,'dev/guides/Guide532/Guide.xml','My Interview WORD PASTE','2014-08-29 15:08:29',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,533,'dev/guides/Guide533/Guide.xml','My Interview','2014-08-29 15:08:53',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,534,'Jessica Frank/guides/Guide534/Guide.xml','My Interview','2014-08-29 15:12:00',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,535,'Jessica Frank/guides/Guide535/Guide.xml','My Interview','2014-08-29 15:12:54',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,536,'dev/guides/Guide536/Guide.xml','My Interview','2014-08-29 15:38:49',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,537,'dev/guides/Guide537/Guide.xml','My Interview','2014-08-29 15:46:19',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (1,1,1,538,'A2J/guides/DemoRepeats/Jess Repeat Loop.a2j5','Repeat Loop Example','2014-09-04 12:12:24',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,539,'dev/guides/Guide539/Guide.xml','My Interview (9/18/2014)','2014-09-18 12:29:25',NULL,NULL,0,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,540,'Jessica Frank/guides/Guide540/Guide.xml','My Interview (9/22/2014)','2014-09-22 13:49:40',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,541,'Jessica Frank/guides/Guide541/Guide.xml','My Interview (9/23/2014)','2014-09-23 15:52:44',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,542,'dev/guides/Guide542/Guide.xml','My Interview (9/25/2014)','2014-09-25 13:39:55',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,543,'dev/guides/Guide543/Guide.xml','Capacity Interview','2014-09-30 13:30:41',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,544,'dev/guides/Guide544/Guide.xml','Capacity Interview','2014-09-30 13:32:54',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,545,'dev/guides/Guide545/Guide.xml','Variable Macros Training GI Jessica attempt ','2014-10-01 14:02:11',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,546,'dev/guides/Guide546/Guide.xml','Variable Macros Training GI Jessica attempt ','2014-10-01 14:16:26',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,547,'dev/guides/Guide547/Guide.xml','Variable Macros Training GI Jessica attempt ','2014-10-01 14:18:51',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,548,'dev/guides/Guide548/Guide.xml','Variable Macros Training GI Jessica attempt ','2014-10-01 14:22:22',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,549,'dev/guides/Guide549/Guide.xml','Variable Macros Training GI Jessica attempt ','2014-10-01 14:44:16',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,550,'dev/guides/Guide550/Guide.xml','Variable Macros Training GI Jessica attempt ','2014-10-01 15:54:03',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,551,'dev/guides/Guide551/Guide.xml','Variable Macros Training GI Jessica attempt ','2014-10-01 16:01:42',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,552,'dev/guides/Guide552/Guide.xml','Jessica all inclusive test 2','2014-10-16 11:26:30',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,553,'dev/guides/Guide553/Guide.xml','TestLocal - 2015-02-27 <\\\'&\\\'> Test 2 All Field Chars','2014-10-16 11:27:06',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,554,'dev/guides/Guide554/Guide.xml','LOCALHOST - Test Field Types PRIME','2014-10-16 11:49:39',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,555,'dev/guides/Guide555/Guide.xml','Jessica all inclusive test 2','2014-10-16 11:52:39',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,556,'Jessica Frank/guides/Guide556/Guide.xml','My Interview (10/27/2014)','2014-10-27 13:32:08',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,557,'Jessica Frank/guides/Guide557/Guide.xml','My Interview (10/29/2014)','2014-10-29 13:53:34',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (116,NULL,NULL,558,'arabanal/guides/Guide558/Guide.xml','Variable Macros Training GI','2014-10-29 15:11:12',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (116,NULL,NULL,559,'arabanal/guides/Guide559/Guide.xml','Wyoming Petition for Guardianship of a Minor (Take 7)','2014-11-05 12:17:25',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,560,'dev/guides/Guide560/Guide.xml','Wyoming Petition for Guardianship of a Minor (Take 7)','2014-11-05 16:24:56',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,561,'dev/guides/Guide561/Guide.xml','Wyoming Petition for Guardianship of a Minor (Take 7)','2014-11-05 16:26:09',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,562,'dev/guides/Guide562/Guide.xml','Wyoming Petition for Guardianship of a Minor (Take 7)','2014-11-05 16:26:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,563,'dev/guides/Guide563/Guide.xml','Wyoming Petition for Guardianship of a Minor (Take 7)','2014-11-05 16:28:14',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,564,'dev/guides/Guide564/Guide.xml','Wyoming Petition for Guardianship of a Minor (Take 7)','2014-11-05 16:33:03',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (116,NULL,NULL,565,'arabanal/guides/Guide565/Guide.xml','My Interview (11/6/2014)','2014-11-06 10:00:06',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,566,'dev/guides/Guide566/Guide.xml','Justice & Technology Practicum, 11/5/2014 - Advanced Topics','2014-11-06 10:48:04',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,567,'dev/guides/Guide567/Guide.xml','Justice & Technology Practicum, 11/5/2014 - Advanced Topics','2014-11-06 13:06:42',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,568,'dev/guides/Guide568/Guide.xml','Wyoming Petition for Guardianship of a Minor (Take 7)','2014-11-06 13:07:55',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,569,'dev/guides/Guide569/Guide.xml','Justice & Technology Practicum, 11/5/2014 - Advanced Topics','2014-11-06 13:10:53',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,570,'dev/guides/Guide570/Guide.xml','Wyoming Petition for Guardianship of a Minor (Take 7)','2014-11-06 13:11:43',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,571,'dev/guides/Guide571/Guide.xml','Justice & Technology Practicum, 11/5/2014 - Advanced Topics','2014-11-06 13:13:35',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,572,'dev/guides/Guide572/Guide.xml','Justice & Technology Practicum, 11/5/2014 - Advanced Topics','2014-11-06 13:15:11',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,573,'dev/guides/Guide573/Guide.xml','Justice & Technology Practicum, 11/5/2014 - Advanced Topics','2014-11-06 13:15:50',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,574,'dev/guides/Guide574/Guide.xml','Justice & Technology Practicum, 11/5/2014 - Advanced Topics','2014-11-06 13:18:04',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,575,'dev/guides/Guide575/Guide.xml','Joint Simplified Dissolution','2014-11-06 13:46:26',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (116,NULL,NULL,576,'arabanal/guides/Guide576/Guide.xml','Wyoming Petition for Guardianship of a Minor (Take 7)','2014-11-06 13:47:11',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (116,NULL,NULL,577,'arabanal/guides/Guide577/Guide.xml','Wyoming Petition for Guardianship of a Minor (Take 7)','2014-11-06 13:48:13',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (116,NULL,NULL,578,'arabanal/guides/Guide578/Guide.xml','Justice & Technology Practicum, 11/5/2014 - Advanced Topics','2014-11-06 13:48:33',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,579,'dev/guides/Guide579/Guide.xml','My Interview (11/3/2014)','2014-11-06 14:12:21',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,580,'dev/guides/Guide580/Guide.xml','Certificate of Relief From Disability Interview','2014-11-06 17:34:57',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,581,'00000/guides/Guide581/Guide.xml','Untitled uploaded guide','2014-11-10 16:08:18',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,582,'00000/guides/Guide582/Guide.xml','Untitled uploaded guide','2014-11-10 16:08:27',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,583,'dev/guides/Guide583/Guide.xml','Lawyer or Me? (11/17/2014)','2014-11-17 13:06:09',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,584,'dev/guides/Guide584/Guide.xml','NOT UPDATED Wyoming Petition for Guardianship of a Minor','2014-11-17 14:35:35',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,585,'dev/guides/Guide585/Guide.xml','NOT UPDATED Wyoming Petition for Guardianship of a Minor','2014-11-17 14:36:15',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,586,'dev/guides/Guide586/Guide.xml','NOT UPDATED Wyoming Petition for Guardianship of a Minor','2014-11-17 14:43:50',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,587,'dev/guides/Guide587/Guide.xml','Wyoming Petition for Guardianship of a Minor (Take 9)','2014-11-18 11:25:45',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,588,'dev/guides/Guide588/Guide.xml','Wyoming Petition for Guardianship of a Minor (Take 9)','2014-11-18 11:32:11',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,589,'dev/guides/Guide589/Guide.xml','v2 CCR Interview','2014-11-18 11:35:10',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,590,'dev/guides/Guide590/Guide.xml','TestLocal - LIST TEST My Interview (11/24/2014)','2014-11-24 15:08:00',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,591,'dev/guides/Guide591/Guide.xml','My Interview (11/5/2014)','2014-11-24 16:23:54',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,592,'dev/guides/Guide592/Guide.xml','My Interview (11/5/2014)','2014-11-28 14:21:19',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,593,'dev/guides/Guide593/Guide.xml','TestLocal - Simple Interview with Answer types and repeat loops (12/31/2014)','2014-12-15 12:18:12',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,594,'dev/guides/Guide594/Guide.xml','Sample Short Interview for Server Test','2015-03-05 13:51:56',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,595,'dev/guides/Guide595/Guide.xml','TestLocal Hyperlinks (5/22/2015)','2015-05-22 12:25:45',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,596,'Jessica Frank/guides/Guide596/Guide.xml','My Interview (6/2/2015)','2015-06-02 15:54:28',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (11,NULL,NULL,597,'Jessica Frank/guides/Guide597/Guide.xml','My Interview (6/2/2015)','2015-06-02 16:26:55',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,598,'dev/guides/Guide598/Guide.xml','My Interview (6/10/2015)','2015-06-10 15:32:47',NULL,NULL,0,NULL,NULL,NULL,NULL,0);
insert into `guides` (`editoruid`,`isPublic`,`isFree`,`gid`,`filename`,`title`,`created`,`CALIcode`,`CALIowned`,`clonedfromgid`,`owner`,`notes`,`alias`,`CALIid`,`archive`) values (45,NULL,NULL,599,'dev/guides/Guide599/Guide.xml','My Interview (6/29/2015)','2015-06-29 16:22:15',NULL,NULL,0,NULL,NULL,NULL,NULL,0);


SET SQL_MODE=@OLD_SQL_MODE;