export const testPages = [
  {
    name: '1-Introduction',
    text: '<p>This is the introduction. Find this use of variable -&gt;  %%[Foo]%%</p>',
    textCitation: '',
    textAudioURL: '',
    notes: '',
    learn: '',
    help: '',
    helpCitation: '',
    helpMediaLabel: '',
    helpAudioURL: '',
    helpReader: '',
    helpImageURL: '',
    helpAltText: '',
    helpVideoURL: '',
    repeatVar: 'Foo',
    outerLoopVar: 'Foo',
    codeBefore: 'set [Foo] to "before"<BR/>',
    codeAfter: 'set [Foo] to "after"<BR/>',
    codeCitation: '',
    fields: [
      {
        type: 'text',
        label: 'Label',
        name: 'Foo',
        value: '',
        required: false,
        invalidPrompt: '',
        invalidPromptAudio: '',
        order: '',
        min: '',
        max: '',
        calculator: false,
        maxChars: '',
        listSrc: '',
        listData: '',
        sample: ''
      }
    ],
    buttons: [
      {
        label: 'Continue',
        next: '2-Name %%Foo%%',
        url: '',
        name: 'Foo',
        value: '',
        repeatVar: 'Foo',
        repeatVarSet: '',
        message: ''
      }
    ],
    step: 0,
    type: 'A2J',
    style: '',
    mapx: 60,
    mapy: 60,
    mapBranches: null,
    xml: '<TEXT><p>This is the introduction. Find this use of variable -&gt;  %%[Foo]%%</p></TEXT><BUTTONS><BUTTON NEXT="2-Name %%Foo%%" REPEATVAR="Foo"><LABEL>Continue</LABEL><NAME>Foo</NAME></BUTTON></BUTTONS><FIELDS><FIELD TYPE="text" REQUIRED="false" CALCULATOR="false"><LABEL>Label</LABEL><NAME>Foo</NAME></FIELD></FIELDS><CODEBEFORE>set [Foo] to "before"<BR/></CODEBEFORE><CODEAFTER>set [Foo] to "after"<BR/></CODEAFTER>',
    nested: false
  },
  {
    name: '1-Question 1',
    text: '<P><FONT>Text of my first question goes here.</FONT></P>',
    textCitation: '',
    textAudioURL: '',
    notes: '',
    learn: '',
    help: '',
    helpCitation: '',
    helpMediaLabel: '',
    helpAudioURL: '',
    helpReader: '',
    helpImageURL: '',
    helpAltText: '',
    helpVideoURL: '',
    repeatVar: '',
    outerLoopVar: '',
    codeBefore: '',
    codeAfter: '',
    codeCitation: '',
    fields: [],
    buttons: [
      {
        label: 'Save',
        next: 'SUCCESS',
        url: '',
        name: '',
        value: '',
        repeatVar: '',
        repeatVarSet: '',
        message: ''
      }
    ],
    step: 1,
    type: 'A2J',
    style: '',
    mapx: 240,
    mapy: 60,
    mapBranches: null,
    xml: '<TEXT><P><FONT>Text of my first question goes here.</FONT></P></TEXT><BUTTONS><BUTTON NEXT="SUCCESS"><LABEL>Save</LABEL></BUTTON></BUTTONS>',
    nested: false
  },
  {
    name: '2-Name %%Foo%%',
    text: '<p>Enter your name. </p>',
    textCitation: '',
    textAudioURL: '',
    notes: '',
    learn: '',
    help: '',
    helpCitation: '',
    helpMediaLabel: '',
    helpAudioURL: '',
    helpReader: '',
    helpImageURL: '',
    helpAltText: '',
    helpVideoURL: '',
    repeatVar: '',
    outerLoopVar: '',
    codeBefore: '',
    codeAfter: 'SET [Foo 123] to "second"<BR/>',
    codeCitation: '',
    fields: [
      {
        type: 'text',
        label: 'First:',
        name: 'Client first name TE',
        value: '',
        required: true,
        invalidPrompt: '',
        invalidPromptAudio: '',
        order: 'ASC',
        min: '',
        max: '',
        calculator: false,
        maxChars: '',
        listSrc: '',
        listData: '',
        sample: ''
      },
      {
        type: 'text',
        label: 'Middle:',
        name: 'Client middle name TE',
        value: '',
        required: false,
        invalidPrompt: '',
        invalidPromptAudio: '',
        order: 'ASC',
        min: '',
        max: '',
        calculator: false,
        maxChars: '',
        listSrc: '',
        listData: '',
        sample: ''
      },
      {
        type: 'text',
        label: 'Last:',
        name: 'Client last name TE',
        value: '',
        required: true,
        invalidPrompt: '',
        invalidPromptAudio: '',
        order: 'ASC',
        min: '',
        max: '',
        calculator: false,
        maxChars: '',
        listSrc: '',
        listData: '',
        sample: ''
      }
    ],
    buttons: [
      {
        label: 'Continue',
        next: '3-Avatar',
        url: '',
        name: '',
        value: '',
        repeatVar: '',
        repeatVarSet: '',
        message: ''
      }
    ],
    step: 0,
    type: 'A2J',
    style: '',
    mapx: 60,
    mapy: 300,
    mapBranches: null,
    xml: '<TEXT><p>Enter your name. </p></TEXT><BUTTONS><BUTTON NEXT="3-Avatar"><LABEL>Continue</LABEL></BUTTON></BUTTONS><FIELDS><FIELD TYPE="text" ORDER="ASC" REQUIRED="true" CALCULATOR="false"><LABEL>First:</LABEL><NAME>Client first name TE</NAME></FIELD><FIELD TYPE="text" ORDER="ASC" REQUIRED="false" CALCULATOR="false"><LABEL>Middle:</LABEL><NAME>Client middle name TE</NAME></FIELD><FIELD TYPE="text" ORDER="ASC" REQUIRED="true" CALCULATOR="false"><LABEL>Last:</LABEL><NAME>Client last name TE</NAME></FIELD></FIELDS><CODEAFTER>SET [Foo 123] to "second"<BR/></CODEAFTER>',
    nested: false
  },
  {
    name: '3-Avatar',
    text: 'Choose your avatar.',
    textCitation: '',
    textAudioURL: '',
    notes: '',
    learn: '',
    help: '',
    helpCitation: '',
    helpMediaLabel: '',
    helpAudioURL: '',
    helpReader: '',
    helpImageURL: '',
    helpAltText: '',
    helpVideoURL: '',
    repeatVar: 'Foo-42',
    outerLoopVar: 'Foo-42',
    codeBefore: '',
    codeAfter: 'SET [Foo-42] TO "third"<BR/>',
    codeCitation: '',
    fields: [
      {
        type: 'useravatar',
        label: 'Avatar:',
        name: 'User Avatar',
        value: '',
        required: false,
        invalidPrompt: '',
        invalidPromptAudio: '',
        order: '',
        min: '',
        max: '',
        calculator: false,
        maxChars: '',
        listSrc: '',
        listData: '',
        sample: ''
      },
      {
        type: 'text',
        label: 'Label',
        name: 'Foo-42',
        value: '',
        required: false,
        invalidPrompt: '',
        invalidPromptAudio: '',
        order: '',
        min: '',
        max: '',
        calculator: false,
        maxChars: '',
        listSrc: '',
        listData: '',
        sample: ''
      }
    ],
    buttons: [
      {
        label: 'Continue',
        next: '1-Question 1',
        url: '',
        name: 'Foo-42',
        value: '',
        repeatVar: 'Foo-42',
        repeatVarSet: '',
        message: ''
      }
    ],
    step: 0,
    type: 'A2J',
    style: '',
    mapx: 60,
    mapy: 540,
    mapBranches: null,
    xml: '<TEXT>Choose your avatar.</TEXT><BUTTONS><BUTTON NEXT="1-Question 1" REPEATVAR="Foo-42"><LABEL>Continue</LABEL><NAME>Foo-42</NAME></BUTTON></BUTTONS><FIELDS><FIELD TYPE="useravatar" REQUIRED="false" CALCULATOR="false"><LABEL>Avatar:</LABEL><NAME>User Avatar</NAME></FIELD><FIELD TYPE="text" REQUIRED="false" CALCULATOR="false"><LABEL>Label</LABEL><NAME>Foo-42</NAME></FIELD></FIELDS><CODEAFTER>SET [Foo-42] TO "third"<BR/></CODEAFTER>',
    nested: false
  }
]

export const expectedGreedyHtml = 'Used in 3 pages<ul><li>1-Introduction</li><ul><li>Question Text<li>Counting Variable<li>Outer Loop Variable<li>Before Logic<li>After Logic<li>Field Variable<li>Button Variable Name<li>Button Counting Variable</ul><li>2-Name</li><ul><li>After Logic</ul><li>3-Avatar</li><ul><li>After Logic</ul></ul>'
export const expectedExplicitHtml = 'Used in 1 pages<ul><li>1-Introduction</li><ul><li>Question Text<li>Counting Variable<li>Outer Loop Variable<li>Before Logic<li>After Logic<li>Field Variable<li>Button Variable Name<li>Button Counting Variable</ul>'
