import DefineMap from 'can-define/map/map'
import Component from 'can-component'
import template from './health-tab.stache'

export const GuideHealthReport = DefineMap.extend('GuideHealthReport', {
  guideId: { default: '' }, // generated by author app
  authorId: { default: '' }, // number tied to author login, coerce to string
  title: { default: '' }, // author set
  version: { default: '' }, // author set version
  createdate: { default: '' }, // this gets set on GI creation
  modifydate: { default: '' }, // does this update on save?
  emailContact: { default: '' }, // email tobias
  sortedPages: [], // iterate guide.sortedPages and sum up messages
  vars: [] // isUnused
})

export const HealthTabVM = DefineMap.extend('HealthTabVM', {
  // passed in via app.stache
  guide: {},
  guideId: {},
  waiting: {
    type: 'boolean',
    default: false
  },
  get vars () { return this.guide && this.guide.vars },

  get pages () { return this.guide && this.guide.pages },

  get fields () {
    const fields = []

    this.guide.pages.forEach(page => fields.push(...page.fields.splice(0)))

    return fields
  },

  connectedCallback () {
    // createHealthChecks(checks:[]) - returns a runHealthCheck function
    // use compute for results of runHealtCheck
    // check: {page: }
    // this.guide.forEach(prop => console.log('prop', prop))
    const guide = this.guide
    const guideId = this.guideId

    console.log('g', guide)

    const { authorId, title, version, createdate, modifydate, emailContact, sortedPages, vars } = guide
    const ghr = new GuideHealthReport({ guideId, authorId, title, version, createdate, modifydate, emailContact, sortedPages, vars })

    guide.sortedPages.forEach(page => {
      // check buttons
      // check fields/var types
      // check logic?
    })
    console.log('stuffs', ghr)
  }
})

export default Component.extend({
  tag: 'health-tab',
  view: template,
  leakScope: false,
  ViewModel: HealthTabVM
})
