import 'caja/viewer/mobile/util/tests/lang-test'
import 'caja/viewer/mobile/util/tests/logic-test'
import 'caja/viewer/mobile/util/tests/parser-test'
import 'caja/viewer/mobile/util/tests/validations-test'
import 'caja/viewer/mobile/util/tests/string-test'
import 'caja/viewer/mobile/util/tests/date-test'
import 'caja/viewer/mobile/util/tests/tlogic-test'
import 'caja/viewer/mobile/util/tests/helpers-test'
