import 'a2jauthor/models/fixtures/'
import 'a2jauthor/models/tests/guide-test'
import 'a2jauthor/models/tests/a2j-node-test'
import 'a2jauthor/models/tests/app-state-test'
import 'a2jauthor/models/tests/a2j-template-test'
import 'a2jauthor/models/tests/a2j-variable-test'
import 'a2jauthor/models/tests/trace-message-test'
import 'a2jauthor/utils/move-item-array-test'
import 'a2jauthor/utils/eval-author-condition-test'

import 'a2jdeps/alert/alert-test'
import 'a2jauthor/popover/popover-test'
import 'a2jauthor/report/report-test'
import 'a2jauthor/templates/templates-test'
import 'a2jauthor/templates/edit/edit-test'
import 'a2jauthor/templates/edit/toolbar/toolbar-test'
import 'a2jauthor/interviews/interviews-test'
import 'a2jauthor/loading/loading-test'
import 'a2jauthor/templates/list/item/item-test'
import 'a2jauthor/templates/list/sortbar/sortbar-test'
import 'a2jauthor/vertical-navbar/vertical-navbar-test'
import 'a2jauthor/templates/elements/varpicker/varpicker-test'
import 'a2jauthor/templates/elements/a2j-template/a2j-template-test'
import 'a2jauthor/templates/elements/a2j-variable/a2j-variable-test'
import 'a2jauthor/templates/elements/options-pane/options-pane-test'
import 'a2jauthor/templates/elements/a2j-repeat-loop/a2j-repeat-loop-test'
import 'a2jauthor/templates/elements/a2j-conditional/a2j-conditional-test'
import 'a2jauthor/templates/elements/a2j-template-ssr/a2j-template-ssr-test'
import 'a2jauthor/templates/elements/a2j-header-footer/a2j-header-footer-test'
import 'a2jauthor/templates/elements/element-container/element-container-test'

import 'a2jauthor/debug-panel/debug-panel-test'

import 'a2jauthor/pdf/assemble-test'
import 'a2jauthor/pdf/editor/area-test'
import 'a2jauthor/pdf/editor/editor-test'
import 'a2jauthor/pdf/checkmark-picker/checkmark-picker-test'
import 'a2jauthor/user-avatar-picker/user-avatar-picker-test'

import 'a2jauthor/src/a2j-legacy-tests'
