/*
	A2J Author 5 * Justice * 正义 * công lý * 사법 * правосудие * sprawiedliwość
	All Contents Copyright The Center for Computer-Assisted Legal Instruction

	Language (INCOMPLETE)
	Language file for the authoring tool
	Language blocks for each supported language.
	There's a Languages[] structure for A2J Viewer specific code.
	And jQuery UI structs for Calendar.

	Currently supported languages:
		English
		Spanish
		Vietnamese
		Chinese-Simplified
		Korean
		French
		Polish
		Russian
		Dutch
		Albanian
		Arabic
		Bengali
		Chaldean
		Hmong

	Pending:

	2015 - 07/14/2012

*/
// TODO: fix legacy imports, removing circular dependencies
// import {makestr} from './A2J_Shared'

// Language elements that are translatable
var lang = {
  Language: '',
  AskYesNo_Yes: '',
  AskYesNo_No: '',
  Close: '',
  Comment: '',
  GoBack: '',
  GoNext: '',
  LearnMore: '',
  MyProgress: '',
  ProvideFeedbackOrComment: '',
  SaveAndExit: '',
  ResumeExit: '',
  SendFeedback: '',
  SoundIsOff: '',
  SoundIsOn: '',
  SoundPlay: '',
  SoundStop: '',
  WhatDoYouMean: '',
  Continue: '',
  Exit: '',
  Male: '',
  Female: '',
  ChooseListNumber: ':',
  ChooseListText: '',
  CheckBoxNOTALabel: '',
  ZoomNormal: '',
  ZoomFull: '',
  TextEnlarge: '',
  TextShrink: '',
  TextSizeLetter: '',
  UploadAnswers: '',
  CalcClear: '',
  CalcEnter: '',
  MonthNamesShort: '',
  MonthNamesLong: '',
  FieldPrompts_ResponseRequired: '',
  FieldPrompts_SelectionRequired: '',
  FieldPrompts_text: '',
  FieldPrompts_textlong: '',
  FieldPrompts_textpick: '',
  FieldPrompts_number: '',
  FieldPrompts_numberdollar: '',
  FieldPrompts_numberssn: '',
  FieldPrompts_numberphone: '',
  FieldPrompts_numberzip: '',
  FieldPrompts_numberpick: '',
  FieldPrompts_datemdy: '',
  FieldPrompts_gender: '',
  FieldPrompts_radio: '',
  FieldPrompts_checkbox: '',
  FieldPrompts_checkboxNOTA: '',
  Ordinals_1: '',
  Ordinals_2: '',
  Ordinals_3: '',
  Ordinals_4: '',
  Ordinals_5: '',
  Ordinals_6: '',
  Ordinals_7: '',
  Ordinals_8: '',
  Ordinals_9: '',
  Ordinals_10: '',
  Ordinals_11: '',
  Ordinals_12: '',
  Ordinals_13: '',
  RepeatAnd: '' // Used in building comma list from REPEAT.
}

function readableList (list) {	// 2014-09-03 Return comma separated, optional 'and' for array.
  var items = []
  for (var i in list) {	// Remove null or blanks.
    var item = list[i]
    if (!isBlankOrNull(item)) {
      items.push(item)
    }
  }
  var text = items.pop()
  if (items.length > 0) {
    text = items.join(', ') + ' ' + lang.RepeatAnd + ' ' + text
  }
  return text
}
/**
 * @constructor
 * @struct
 * @this {TLanguages}
 */
function TLanguages () {
  this.defaultLanguage = 'en'
  this.regional = {}
  this.set = /** @this {TLanguages} */ function (languageID) {
    if (typeof this.regional[languageID] === 'undefined') {
      languageID = 'en'
    }
    // trace("TLanguages.set",languageID);
    var region

    region = this.regional[languageID]
    var e
    for (e in region) {
      if (region.hasOwnProperty(e)) {
        lang[e] = String(region[e])
      }
    }

    region = this.regional.en
    for (e in region) {
      if (region.hasOwnProperty(e)) {
        if (makestr(lang[e]) === '') {
          lang[e] = String(region[e])
          // traceAlert('Missing '+e+"="+lang[e]);
        }
      }
    }
  }

  this.en = function (txt) {	// needs translation
    return txt
  }

  return this
}

var Languages = new TLanguages()

/* 05/05/2005, 03/11/2010 English language file used with A2J Viewer' */
Languages.regional.en = {
  locale: 'en',
  Language: 'English',
  LanguageEN: 'English',
  AskYesNo_Yes: 'Yes',
  AskYesNo_No: 'No',
  Close: 'Close',
  Comment: 'Comment',
  GoBack: 'Back',
  GoNext: 'Next',
  LearnMore: 'Learn More',
  MyProgress: 'MY PROGRESS',
  ProvideFeedbackOrComment: 'Provide feedback or comment on this page',
  SaveAndExit: 'EXIT',
  ResumeExit: 'RESUME',
  SendFeedback: 'SEND FEEDBACK',
  SoundIsOff: 'SOUND IS OFF',
  SoundIsOn: 'SOUND IS ON',
  SoundPlay: 'Play',
  SoundStop: 'Stop',
  WhatDoYouMean: 'What do you mean?',
  Continue: 'Continue',
  Exit: 'Exit',
  Male: 'Male',
  Female: 'Female',
  ChooseListNumber: 'Choose:',
  ChooseListText: 'Choose from this list:',
  CheckBoxNOTALabel: 'None of the above',
  ZoomNormal: 'Normal Size',
  ZoomFull: 'Full screen',
  TextEnlarge: 'Enlarge text box',
  TextShrink: 'Shrink text box',
  TextSizeLetter: 'A',
  UploadAnswers: 'Exiting. Please wait...',
  CalcClear: 'Clear',
  CalcEnter: 'Enter',
  MonthNamesShort: 'Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec',
  MonthNamesLong: 'January,February,March,April,May,June,July,August,September,October,November,December',
  FieldPrompts_ResponseRequired: 'You must provide a response in the blanks next to the red labels before you can continue.',
  FieldPrompts_SelectionRequired: 'You must make a selection before you can continue.',
  FieldPrompts_text: 'You must type a response in the highlighted space before you can continue.',
  FieldPrompts_textlong: 'You must type a response in the highlighted space before you can continue.',
  FieldPrompts_textpick: 'You must make a selection from the highlighted space before you can continue.',
  FieldPrompts_number: 'You must type a number in the highlighted space before you can continue.',
  FieldPrompts_numberdollar: 'You must type a dollar amount in the highlighted space before you can continue.',
  FieldPrompts_numberssn: 'You must type a social security number in the highlighted spaces before you can continue.',
  FieldPrompts_numberphone: 'You must type a phone number in the highlighted spaces before you can continue.',
  FieldPrompts_numberzip: 'You must type a zip code in the highlighted space before you can continue.',
  FieldPrompts_numberpick: 'You must select a number from the highlighted space before you can continue.',
  FieldPrompts_datemdy: 'You must enter a month, day and year in the highlighted spaces before you can continue.',
  FieldPrompts_gender: 'Select an avatar to represent you.',
  FieldPrompts_radio: 'You must choose a response from the highlighted selection before you can continue.',
  FieldPrompts_checkbox: 'You must select one or more checkboxes to continue.',
  FieldPrompts_checkboxNOTA: 'Please select one or more checkboxes or "None of the above" to continue.',
  Ordinals_1: 'first',
  Ordinals_2: 'second',
  Ordinals_3: 'third',
  Ordinals_4: 'fourth',
  Ordinals_5: 'fifth',
  Ordinals_6: 'sixth',
  Ordinals_7: 'seventh',
  Ordinals_8: 'eighth',
  Ordinals_9: 'ninth',
  Ordinals_10: 'tenth',
  Ordinals_11: 'eleventh',
  Ordinals_12: 'twelfth',
  Ordinals_13: '13th',
  RepeatAnd: 'and',

  // Authoring system, non-translated elements.
  // Tab names
  tabAbout: 'About',
  tabInterview: 'Interview',
  tabVariables: 'Variables',
  tabSteps: 'Steps',
  // Question branching types
  qIDNOWHERE: '[no where]',
  qIDSUCCESS: '[Success - Process Form]',
  qIDFAIL: '[Exit - User does not qualify]',
  qIDEXIT: '[Exit - Save Incomplete Form]',
  qIDBACK: '[Back to prior question]',
  qIDRESUME: '[Resume interview]',
  qIDASSEMBLE: '[Assemble - Generate PDF document]',
  qIDASSEMBLESUCCESS: '[Assemble - Generate PDF and Process Form]',

  // Unknown ID
  UnknownID: '[Unknown id [{1}]: [{2}]',

  scriptErrorMissingPage: 'Page "{1}" does not exist.',
  scriptErrorUnhandled: 'Unknown command: {1}',
  scriptErrorEndMissing: 'Missing an EndIf'

}

// Albanian
Languages.regional.sq = {
  locale: 'sq',
  Language: 'Shqip',
  LanguageEN: 'Albanian',
  AskYesNo_Yes: 'Po',
  AskYesNo_No: 'Jo',
  Close: 'Mbyllni',
  Comment: 'Komentoni',
  GoBack: 'Prapa',
  GoNext: 'Para',
  LearnMore: 'Mësoni më shumë',
  MyProgress: 'PËRPARIMI IM',
  ProvideFeedbackOrComment: 'Reagoni ose komentoni mbi këtë faqe',
  SaveAndExit: 'DALJA',
  ResumeExit: 'RIFILLIM',
  SendFeedback: 'REAGIM',
  SoundIsOff: 'PA ZË',
  SoundIsOn: 'ME ZË',
  SoundPlay: 'Hapni',
  SoundStop: 'Ndal',
  WhatDoYouMean: 'Çfarë doni të thoni?',
  Continue: 'Vazhdoni',
  Exit: 'Dalja',
  Male: 'Mashkull',
  Female: 'Femër',
  ChooseListNumber: 'Zgjidhni:',
  ChooseListText: 'Zgjidhni nga kjo listë:',
  CheckBoxNOTALabel: 'Asnjë nga të mësipërmet',
  ZoomNormal: 'Masë normale',
  ZoomFull: 'Ekran i plotë',
  TextEnlarge: 'Zmadhoni kutinë e tekstit',
  TextShrink: 'Zvogëloni kutinë e tekstit',
  TextSizeLetter: 'A',
  UploadAnswers: 'Duke dalë. Ju lutem prisni...',
  CalcClear: 'Fshirje',
  CalcEnter: 'Komanda Enter',
  MonthNamesShort: 'janar, shkurt, mars, prill, maj, qershor, korrik, gusht, shtator, tetor, nëntor, dhjetor',
  MonthNamesLong: 'janar, shkurt, mars, prill, maj, qershor, korrik, gusht, shtator, tetor, nëntor, dhjetor',
  FieldPrompts_ResponseRequired: 'Para se të vazhdoni, duhet të përgjigjeni në vendet bosh ngjitur me emërtimet në të kuqe.',
  FieldPrompts_SelectionRequired: 'Zgjidhni para se të vazhdoni.',
  FieldPrompts_text: 'Shënoni përgjigjen në vendet e theksuara para se të vazhdoni.',
  FieldPrompts_textlong: 'Shënoni përgjigjen në vendet e theksuara para se të vazhdoni.',
  FieldPrompts_textpick: 'Para se të vazhdoni, duhet të zgjidhni nga vendet e theksuara.',
  FieldPrompts_number: 'Para se të vazhdoni, duhet të shtypni në vendet e theksuara.',
  FieldPrompts_numberdollar: 'Para se të vazhdoni, shënoni shumën në dollarë në vendet e theksuara.',
  FieldPrompts_numberssn: 'Para se të vazhdoni, duhet të shënoni numrin e sigurimeve shoqërore në vendet e theksuara.',
  FieldPrompts_numberphone: 'Para se të vazhdoni, shënoni numrin numrin e telefonit në vendet e theksuara.',
  FieldPrompts_numberzip: 'Para se të vazhdoni, shënoni kodin postar në vendet e theksuara.',
  FieldPrompts_numberpick: 'Para se të vazhdoni, zgjidhni një numër nga vendet e theksuara.',
  FieldPrompts_datemdy: 'Para se të vazhdoni, vendosni një muaj, ditë dhe vit në vendet e theksuara.',
  FieldPrompts_gender: 'Para se të vazhdoni, duhet të zgjidhni gjininë mashkullore ose femërore nga përzgjedhja e theksuar.',
  FieldPrompts_radio: 'Para se të vazhdoni, zgjidhni një përgjigje nga përzgjedhja e theksuar.',
  FieldPrompts_checkbox: 'Zgjidhni një ose më shumë nga kutitë përkatëse për të vazhduar më tej.',
  FieldPrompts_checkboxNOTA: 'Ju lutem zgjidhni një ose më shumë nga kutitë përkatëse ose "Asnjë nga të mësipërmet" për të vazhduar më tej.',
  Ordinals_1: 'i pari',
  Ordinals_2: 'i dyti',
  Ordinals_3: 'i treti',
  Ordinals_4: 'i katërti',
  Ordinals_5: 'i pesti',
  Ordinals_6: 'i gjashti',
  Ordinals_7: 'i shtati',
  Ordinals_8: 'i teti',
  Ordinals_9: 'i nënti',
  Ordinals_10: 'i dhjeti',
  Ordinals_11: 'i njëmbëdhjeti',
  Ordinals_12: 'i dymbëdhjeti',
  Ordinals_13: 'i trembëdhjeti'
}

// Arabic
Languages.regional.ar = {
  locale: 'ar',
  Language: 'العربية',
  LanguageEN: 'Arabic',
  AskYesNo_Yes: 'نعم',
  AskYesNo_No: 'لا',
  Close: 'إغلاق',
  Comment: 'تعليق',
  GoBack: 'عودة',
  GoNext: 'التالي',
  LearnMore: 'معرفة المزيد',
  MyProgress: 'تقدمي',
  ProvideFeedbackOrComment: 'قدم رأيك أو تعليقك على هذه الصفحة',
  SaveAndExit: 'خروج',
  ResumeExit: 'متابعة',
  SendFeedback: 'إرسال تعليقات',
  SoundIsOff: 'تم إيقاف الصوت',
  SoundIsOn: 'تم تشغيل الصوت',
  SoundPlay: 'تشغيل',
  SoundStop: 'إيقاف',
  WhatDoYouMean: 'ما الذي تعنيه؟',
  Continue: 'متابعة',
  Exit: 'خروج',
  Male: 'ذكر',
  Female: 'أنثى',
  ChooseListNumber: 'اختر:',
  ChooseListText: 'اختر من هذه القائمة:',
  CheckBoxNOTALabel: 'لا شيء مما سبق',
  ZoomNormal: 'حجم عادي',
  ZoomFull: 'ملء الشاشة',
  TextEnlarge: 'توسعة المربع النصي',
  TextShrink: 'تصغير المربع النصي',
  TextSizeLetter: 'أ',
  UploadAnswers: 'جارٍ الخروج. يرجى الانتظار...',
  CalcClear: 'مسح',
  CalcEnter: 'أدخل',
  MonthNamesShort: 'يناير, فبراير, مارس, أبريل, مايو, يونيو, يوليو, أغسطس, سبتمبر, أكتوبر, نوفمبر, ديسمبر',
  MonthNamesLong: 'يناير, فبراير, مارس, أبريل, مايو, يونيو, يوليو, أغسطس, سبتمبر, أكتوبر, نوفمبر, ديسمبر',
  FieldPrompts_ResponseRequired: 'يجب أن تقدم ردًا في الفراغات بجوار التسميات الحمراء حتى تتمكن من المتابعة.',
  FieldPrompts_SelectionRequired: 'يجب أن تجري تحديدًا حتى تتمكن من المتابعة.',
  FieldPrompts_text: 'يجب أن تكب ردًا في المساحة المميزة حتى تتمك من المتابعة.',
  FieldPrompts_textlong: 'يجب أن تكب ردًا في المساحة المميزة حتى تتمك من المتابعة.',
  FieldPrompts_textpick: 'يجب أن تجري تحديدًا من المساحة المميزة حتى تتمكن من المتابعة.',
  FieldPrompts_number: 'يجب أن تكتب رقمًا في المساحة المميزة حتى تتمكن من المتابعة.',
  FieldPrompts_numberdollar: 'يجب أن تكتب مبلغًا بالدولار في المساحة المميزة حتى تتمكن من المتابعة.',
  FieldPrompts_numberssn: 'يجب أن تكب رقم التأمين الاجتماعي في المساحات المميزة حتى تتمكن من المتابعة.',
  FieldPrompts_numberphone: 'يجب أن تكتب رقم هاتفي في المساحات المميزة حتى تتمكن من المتابعة.',
  FieldPrompts_numberzip: 'يجب أن تكتب رمز بريدي في المساحة المميزة حتى تتمكن من المتابعة.',
  FieldPrompts_numberpick: 'يجب أن تحدد رقمًا من المساحة المميزة حتى تتمكن من المتابعة.',
  FieldPrompts_datemdy: 'يجب أن تدخل شهر ويوم وشنة في المساحات المميزة حتى تتمكن من المتابعة.',
  FieldPrompts_gender: 'يجب أن تختار إما ذكر أو أنثى من التحديد المميز حتى تتمكن من المتابعة.',
  FieldPrompts_radio: 'يجب أن تختار ردًا من التحديد المميز حتى تتمكن من المتابعة.',
  FieldPrompts_checkbox: 'يجب أن تحدد مربع اختيار واحد أو أكثر للمتابعة.',
  FieldPrompts_checkboxNOTA: 'يجب تحديد مربع اختيار واحد أو أكثر أو "لا شيء مما سبق" للمتابعة.',
  Ordinals_1: 'الأول',
  Ordinals_2: 'الثاني',
  Ordinals_3: 'الثالث',
  Ordinals_4: 'الرابع',
  Ordinals_5: 'الخامس',
  Ordinals_6: 'السادس',
  Ordinals_7: 'السابق',
  Ordinals_8: 'الثامن',
  Ordinals_9: 'التاسع',
  Ordinals_10: 'العاشر',
  Ordinals_11: 'الحادي عشر',
  Ordinals_12: 'الثاني عشر',
  Ordinals_13: 'الثالث عشر'
}

// Bengali or Bangla
// Sublime text editor does not render Bengali fonts correctly, but the language
// will show properly in browsers
Languages.regional.bn = {
  locale: 'bn',
  Language: 'বাংলা,',
  LanguageEN: 'Bengali',
  AskYesNo_Yes: 'হ্যাঁ',
  AskYesNo_No: 'না',
  Close: 'বন্ধ করুন',
  Comment: 'মন্তব্য',
  GoBack: 'পিছনে',
  GoNext: 'পরবর্তী',
  LearnMore: 'আরো জানুন',
  MyProgress: 'আমার অগ্রগতি',
  ProvideFeedbackOrComment: 'এই পাতায় মতামত বা মন্তব্য দিন',
  SaveAndExit: 'প্রস্থান',
  ResumeExit: 'আবার শুরু করুন',
  SendFeedback: 'মতামত পাঠান',
  SoundIsOff: 'শব্দ বন্ধ আছে',
  SoundIsOn: 'শব্দ চালু আছে',
  SoundPlay: 'চালান',
  SoundStop: 'থামান',
  WhatDoYouMean: 'আপনার কথার অর্থ কী ?',
  Continue: 'এগিয়ে যান',
  Exit: 'প্রস্থান',
  Male: 'পুরুষ',
  Female: 'মহিলা',
  ChooseListNumber: 'বেছে নিন:',
  ChooseListText: 'এই তালিকা থেকে বেছে নিন:',
  CheckBoxNOTALabel: 'ওপরের কোনোটাই নয়',
  ZoomNormal: 'স্বাভাবিক আকার',
  ZoomFull: 'পূর্ণ স্ক্রীন',
  TextEnlarge: 'টেক্সট বক্স বড় করুন',
  TextShrink: 'টেক্সট বক্স ছোট করুন',
  TextSizeLetter: 'A',
  UploadAnswers: 'প্রস্থান করা হচ্ছে। অনুগ্রহ করে অপেক্ষা করুন...',
  CalcClear: 'সাফ করুন',
  CalcEnter: 'প্রবিষ্ট করুন',
  MonthNamesShort: 'জানুঃ, ফেব্রু, মার্চ, এপ্রিল, মে, জুন, জুলাই, আগস্ট, সেপ্টেঃ, অক্টোঃ, নভেঃ, ডিসেঃ',
  MonthNamesLong: 'জানুয়ারি, ফেব্রুয়ারি, মার্চ, এপ্রিল, মে, জুন, জুলাই, আগস্ট, সেপ্টেম্বর, অক্টোবর, নভেম্বর, ডিসেম্বর',
  FieldPrompts_ResponseRequired: 'আপনি এগোতে সক্ষম হওয়ার আগে লাল লেবেলগুলির পাশের খালি জায়গায় একটা উত্তর আপনাকে অবশ্যই দিতে হবে।',
  FieldPrompts_SelectionRequired: 'আপনি এগোতে সক্ষম হওয়ার আগে আপনাকে অবশ্যই একটি নির্বাচন করতে হবে।',
  FieldPrompts_text: 'আপনি এগোতে সক্ষম হওয়ার আগে হাইলাইট করা জায়গাটিতে আপনাকে অবশ্যই একটি উত্তর টাইপ করতে হবে।',
  FieldPrompts_textlong: 'আপনি এগোতে সক্ষম হওয়ার আগে হাইলাইট করা জায়গাটিতে আপনাকে অবশ্যই একটি উত্তর টাইপ করতে হবে।',
  FieldPrompts_textpick: 'আপনি এগোতে সক্ষম হওয়ার আগে হাইলাইট করা জায়গাটি থেকে আপনাকে অবশ্যই একটি নির্বাচন করতে হবে।',
  FieldPrompts_number: 'আপনি এগোতে সক্ষম হওয়ার আগে হাইলাইট করা জায়গাটিতে আপনাকে অবশ্যই একটি সংখ্যা টাইপ করতে হবে।',
  FieldPrompts_numberdollar: 'আপনি এগোতে সক্ষম হওয়ার আগে হাইলাইট করা জায়গাটিতে আপনাকে অবশ্যই একটি ডলার রাশি টাইপ করতে হবে।',
  FieldPrompts_numberssn: 'আপনি এগোতে সক্ষম হওয়ার আগে আপনাকে হাইলাইট করা জায়গাগুলিতে অবশ্যই একটি সোশ্যাল সিকিওরিটি নম্বর টাইপ করতে হবে।',
  FieldPrompts_numberphone: 'আপনি এগোতে সক্ষম হওয়ার আগে আপনাকে হাইলাইট করা জায়গাগুলিতে অবশ্যই একটি ফোন নম্বর টাইপ করতে হবে।',
  FieldPrompts_numberzip: 'আপনি এগোতে সক্ষম হওয়ার আগে হাইলাইট করা জায়গাটিতে আপনাকে অবশ্যই একটি জিপ কোড টাইপ করতে হবে।',
  FieldPrompts_numberpick: 'আপনি এগোতে সক্ষম হওয়ার আগে হাইলাইট করা জায়গাটি থেকে আপনাকে অবশ্যই একটি সংখ্যা নির্বাচন করতে হবে।',
  FieldPrompts_datemdy: 'আপনি এগোতে সক্ষম হওয়ার আগে হাইলাইট করা জায়গাগুলিতে আপনাকে অবশ্যই মাস, দিন ও বছর দিতে হবে।',
  FieldPrompts_gender: 'আপনি এগোতে সক্ষম হওয়ার আগে হাইলাইট করা নির্বাচনটি থেকে আপনাকে অবশ্যই পুরুষ বা মহিলা বেছে নিতে হবে।',
  FieldPrompts_radio: 'আপনি এগোতে সক্ষম হওয়ার আগে হাইলাইট করা নির্বাচনটি থেকে আপনাকে অবশ্যই একটি উত্তর বেছে নিতে হবে।',
  FieldPrompts_checkbox: 'এগনোর জন্য আপনাকে অবশ্যই একটি বা তার বেশি চেকবক্স নির্বাচন করতে হবে।',
  FieldPrompts_checkboxNOTA: 'এগনোর জন্য অনুগ্রহ করে একটি বা তার বেশি চেকবক্স অথবা "ওপরের কোনোটাই নয়" নির্বাচন করুন।',
  Ordinals_1: 'প্রথম',
  Ordinals_2: 'দ্বিতীয়',
  Ordinals_3: 'তৃতীয়',
  Ordinals_4: 'চতুর্থ',
  Ordinals_5: 'পঞ্চম',
  Ordinals_6: 'ষষ্ঠ',
  Ordinals_7: 'সপ্তম',
  Ordinals_8: 'অষ্টম',
  Ordinals_9: 'নবম',
  Ordinals_10: 'দশম',
  Ordinals_11: 'একাদশতম',
  Ordinals_12: 'দ্বাদশতম',
  Ordinals_13: 'ত্রয়োদশতম'
}

// Chaldean Neo-Aramaic
Languages.regional.cld = {
  locale: 'cld',
  Language: 'إنكليزي',
  LanguageEN: 'Chaldean',
  AskYesNo_Yes: 'أيه',
  AskYesNo_No: 'لا',
  Close: 'جم',
  Comment: 'معالق',
  GoBack: 'رجع بطره',
  GoNext: 'أد بطرو',
  LearnMore: 'لب بعد',
  MyProgress: 'تقدم أدي',
  ProvideFeedbackOrComment: 'ول تقييم أو معالق إلديا صفحة',
  SaveAndExit: 'بلاطة',
  ResumeExit: 'مكمل',
  SendFeedback: 'ول تقييم',
  SoundIsOff: 'قالا هوله جميا',
  SoundIsOn: 'قالا هوله بلهايا',
  SoundPlay: 'مبلخ',
  SoundStop: 'مجميه',
  WhatDoYouMean: 'مهيله قصدخ؟',
  Continue: 'مستمر',
  Exit: 'بلاطا',
  Male: 'ذكر',
  Female: 'أنثى',
  ChooseListNumber: 'مختار',
  ChooseListText: 'مختار من ديا قائمة',
  CheckBoxNOTALabel: 'ولا خا من أد علل',
  ZoomNormal: 'حجم طبيعي',
  ZoomFull: 'شاشة كاملة',
  TextEnlarge: 'مكابر مربع أد كتوتا',
  TextShrink: 'ود مربع أد كتوتا زورا',
  TextSizeLetter: 'أ',
  UploadAnswers: 'ببلاطا. رجاءً منتظرن',
  CalcClear: 'مسح',
  CalcEnter: 'إدخال',
  MonthNamesShort: 'كا٢,شب,اذ,ني,اي,حز,تم,آب,أي,تش١,تش٢,كا١',
  MonthNamesLong: 'كانون الثاني, شباط, اذار, نيسان, ايار, حزيران, تموز, آب, أيلول,تشرين الأول, تشرين الثاني,كانون الأول',
  FieldPrompts_ResponseRequired: 'لازم أوت جواب كو فراغات كيبد قطع حمرة قبل ما مكملت',
  FieldPrompts_SelectionRequired: 'لازم أودت إختيار قبل ما مكملت',
  FieldPrompts_text: 'لازم طبعت جواب كو فراغ مظلل قبل ما مكملت',
  FieldPrompts_textlong: 'لازم طبعت جواب كو فراغ مظلل قبل ما مكملت',
  FieldPrompts_textpick: 'لازم أودت إختيار من فراغ مظلل قبل ما مكملت',
  FieldPrompts_number: 'لازم طبعت رقم كو فراغ مظلل قبل ما مكملت',
  FieldPrompts_numberdollar: 'لازم طبعت قيمة بالدولار كو فراغ مظلل قبل ما مكملت',
  FieldPrompts_numberssn: 'لازم طبعت رقم أد سوشل سيكيوريتي كو فراغ مظلل قبل ما مكملت',
  FieldPrompts_numberphone: 'لازم طبعت رقم أد تلفون كو فراغ مظلل قبل ما مكملت',
  FieldPrompts_numberzip: 'لازم طبعت رمز بريدي زبكود كو فراغ مظلل قبل ما مكملت',
  FieldPrompts_numberpick: 'لازم مختارت رقم من فراغ مظلل قبل ما مكملت',
  FieldPrompts_datemdy: 'لازم مورت شهر، يوم و سنة كو فراغ مظلل قبل ما مكملت',
  FieldPrompts_gender: 'لازم مختارت ياما ذكر أو أنثى من الاختيار المظلل قبل ما مكملت',
  FieldPrompts_radio: 'لازم مختارت جواب من الاختيارات المظللة قبل ما مكملت',
  FieldPrompts_checkbox: 'لازم مختارت خا مربع أو أكثر تمكملت',
  FieldPrompts_checkboxNOTA: 'رجاءً مختار خا مربع أو بش أو ولا خا من أد علل تمكملت',
  Ordinals_1: 'قمايا',
  Ordinals_2: 'أد ترئي',
  Ordinals_3: 'أد طلاتة',
  Ordinals_4: 'أد أربا',
  Ordinals_5: 'أد خمشا',
  Ordinals_6: 'أد اشتى',
  Ordinals_7: 'أد شوا',
  Ordinals_8: 'أد تمنيا',
  Ordinals_9: 'أد تشا',
  Ordinals_10: 'أد اصرة',
  Ordinals_11: 'أد خديسر',
  Ordinals_12: 'أد تريسر',
  Ordinals_13: 'أد تلتاسر'
}

// Spanish language file used with A2J Viewer'
Languages.regional.es = {
  locale: 'es',
  Language: 'Español',
  LanguageEN: 'Spanish',
  AskYesNo_Yes: 'Si',
  AskYesNo_No: 'No',
  Close: 'Cerrar',
  Comment: 'Comentario',
  GoBack: 'Anterior',
  GoNext: 'Siguiente',
  LearnMore: 'Aprender más',
  MyProgress: 'Mi Progreso',
  ProvideFeedbackOrComment: 'Enviar comentarios y sugerencias',
  SaveAndExit: 'Salida',
  ResumeExit: 'Anterior',
  SendFeedback: 'Enviar comentarios',
  SoundIsOff: 'Sonido está apagado',
  SoundIsOn: 'Sonido está encendido',
  SoundPlay: 'Prender',
  SoundStop: 'Parar',
  WhatDoYouMean: '¿Qué significas?',
  Continue: 'continúe',
  Exit: 'Salida',
  Male: 'Masculino',
  Female: 'Femenina',
  ChooseListNumber: 'Escoja:',
  ChooseListText: 'Escoja de esta lista:',
  CheckBoxNOTALabel: 'ninguna de arriba',
  ZoomNormal: 'tamaño normal',
  ZoomFull: 'pantalla completa',
  TextEnlarge: 'ampliar el cuadro de texto',
  TextShrink: 'reducir el cuadro de texto',
  TextSizeLetter: 'A',
  UploadAnswers: 'Saliendo. Por favor, espere...',
  CalcClear: 'Borrar!',
  CalcEnter: 'Calcular!',
  MonthNamesShort: 'ene,feb,mar,abr,may,jun,jul,ago,sep,oct,nov,dic',
  MonthNamesLong: 'enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre',
  FieldPrompts_ResponseRequired: 'Necesita dar una respuesta en los espacios vacios que estan enseguida de los marcadores rojos antes de poder continuar.',
  FieldPrompts_SelectionRequired: 'Debe hacer una selección antes de poder continuar.',
  FieldPrompts_text: 'Debe dar una respuesta en el espacio resaltado antes de poder continuar.',
  FieldPrompts_textlong: 'Debe dar una respuesta en el espacio resaltado antes de poder continuar.',
  FieldPrompts_textpick: 'Debe hacer una selección del area resaltada antes de poder continuar.',
  FieldPrompts_number: 'Debe dar un número en el espacio resaltado antes de poder continuar.',
  FieldPrompts_numberdollar: 'Debe dar una cantidad en dolares en el espacio resaltado antes de poder continuar.',
  FieldPrompts_numberssn: 'Debe proporcionar su número de seguro social en el espacio resaltado antes de poder continuar.',
  FieldPrompts_numberphone: 'Debe dar un número de telêfono en el espacio resaltado antes de poder continuar.',
  FieldPrompts_numberzip: 'Debe escribir un código postal en el espacio resaltado antes de poder continuar.',
  FieldPrompts_numberpick: 'Debe escoger un número del area resaltada antes de poder continuar.',
  FieldPrompts_datemdy: 'Debe dar una fecha que incluya mes, dia y año en el area resaltada antes de poder continuar.',
  FieldPrompts_gender: 'Debe escoger hombre o mujer del area resaltada antes de poder continuar.',
  FieldPrompts_radio: 'Debe escoger una respuesta del area resaltada antes de poder continuar.',
  FieldPrompts_checkbox: 'Por favor seleccione una o mas casillas para continuar.',
  FieldPrompts_checkboxNOTA: 'Por favor seleccione una o mas casillas o "Ninguna de estas" para continuar.',
  Ordinals_1: 'primero',
  Ordinals_2: 'segundo',
  Ordinals_3: 'tercero',
  Ordinals_4: 'cuarto',
  Ordinals_5: 'quinto',
  Ordinals_6: 'sexto',
  Ordinals_7: 'séptimo',
  Ordinals_8: 'octavo',
  Ordinals_9: 'noveno',
  Ordinals_10: 'décimo',
  Ordinals_11: 'undécimo',
  Ordinals_12: 'duodécimo',
  Ordinals_13: 'decimotecero',
  Ordinals_14: 'decimocuarto',
  Ordinals_15: 'decimoquinto',
  Ordinals_16: 'decimosexto',
  Ordinals_17: 'decimoséptimo',
  Ordinals_18: 'decimoctavo',
  Ordinals_19: 'decimonoveno:',
  Ordinals_20: 'vigésimo',
  Ordinals_21: 'vigésimoprimero',
  Ordinals_22: 'vigésimosegundo',
  Ordinals_23: 'vigésimotercero',
  Ordinals_24: 'vigésimocuarto',
  Ordinals_25: 'vigésimoquinto',
  Ordinals_26: 'vigésimosexto',
  Ordinals_27: 'vigésimoséptimo',
  Ordinals_28: 'vigésimooctavo',
  Ordinals_29: 'vigésimonoveno',
  Ordinals_30: 'trigésimo',
  Ordinals_31: 'trigésimoprimero',
  Ordinals_32: 'trigésimosegundo',
  Ordinals_33: 'trigésimotercero',
  Ordinals_34: 'trigésimocuarto',
  Ordinals_35: 'trigésimoquinto',
  Ordinals_36: 'trigésimosexto',
  Ordinals_37: 'trigésimoséptimo',
  Ordinals_38: 'trigésimooctavo',
  Ordinals_39: 'trigésimonoveno',
  Ordinals_40: 'cuadragésimo',
  Ordinals_41: 'cuadragésimoprimero',
  Ordinals_42: 'cuadragésimosegundo',
  Ordinals_43: 'cuadragésimotercero',
  Ordinals_44: 'cuadragésimocuarto',
  Ordinals_45: 'cuadragésimoquinto',
  Ordinals_46: 'cuadragésimosexto',
  Ordinals_47: 'cuadragésimoséptimo',
  Ordinals_48: 'cuadragésimooctavo',
  Ordinals_49: 'cuadragésimonoveno',
  Ordinals_50: 'quincuagésimo',
  RepeatAnd: 'y'
}

// French
Languages.regional.fr = {
  locale: 'fr',
  Language: 'Français',
  LanguageEN: 'French',
  AskYesNo_Yes: 'Oui',
  AskYesNo_No: 'Non',
  Close: 'Fermer',
  Comment: 'Commenter',
  GoBack: 'Retour',
  GoNext: 'Prochain',
  MyProgress: 'MON PROGRÈS',
  ProvideFeedbackOrComment: 'Fournir des suggestions ou des commentaires sur cette page',
  SaveAndExit: 'Sortir',
  ResumeExit: 'Reprendre',
  SendFeedback: 'Envoyer la suggestion',
  SoundIsOff: 'Audio désactivé',
  SoundIsOn: 'Audio activé',
  SoundPlay: 'Jouer',
  SoundStop: 'Arrêt',
  WhatDoYouMean: 'Qu’est- ce que ça signifie?',
  Continue: 'Continuer',
  Exit: 'Sortir',
  Male: 'Mâle',
  Female: 'Femelle',
  ChooseListNumber: 'Choisissez:',
  ChooseListText: 'Aucun des énoncés ',
  ZoomNormal: 'Taille normale',
  ZoomFull: 'Image complète',
  TextEnlarge: 'Agrandir la casse du texte',
  TextShrink: 'Réduire la casse du texte',
  TextSizeLetter: 'A',
  UploadAnswers: 'Veuillez patienter…',
  CalcClear: 'Effacer',
  CalcEnter: 'Entrer',
  MonthNamesShort: 'Janv,Fév,Mars,Avr,Mai,Juin,Juil,Août,Sept,Oct,Nov,Déc',
  MonthNamesLong: 'Janvier,Février,Mars,Avril,Mai,Juin,Juillet,Août,Septembre,Octobre,Novembre,Décembre',
  FieldPrompts_ResponseRequired: 'Remplissez les champs vides à côté des étiquettes rouges pour pouvoir continuer. ',
  FieldPrompts_SelectionRequired: 'Faites un choix pour pouvoir continuer.',
  FieldPrompts_text: 'Entrez une réponse dans le champ surligné pour pouvoir continuer.',
  FieldPrompts_textlong: 'Entrez une réponse dans le champ surligné pour pouvoir continuer.',
  FieldPrompts_textpick: 'Faites un choix à partir de la liste du champ surligné pour pouvoir continuer. ',
  FieldPrompts_number: 'Entrez un numéro dans le champ surligné pour pouvoir continuer.',
  FieldPrompts_numberdollar: 'Entrez un montant dans le champ surligné pour pouvoir continuer. ',
  FieldPrompts_numberssn: 'Entrez votre numéro de sécurité sociale dans le champ surligné pour pouvoir continuer.',
  FieldPrompts_numberphone: 'Entrez votre numéro de téléphone dans le champ surligné pour pouvoir continuer.',
  FieldPrompts_numberzip: 'Entrez votre code postal dans le champ surligné pour pouvoir continuer.',
  FieldPrompts_numberpick: 'Faites un choix à partir de la liste du champ surligné pour pouvoir continuer.',
  FieldPrompts_datemdy: 'Entrez l’année, le mois et le jour dans le champ surligné pour pouvoir continuer.',
  FieldPrompts_gender: 'Choisissez soit mâle soit femelle dans le champ surligné pour pouvoir continuer.',
  FieldPrompts_radio: 'Faites un choix à partir de la liste du champ surligné pour pouvoir continuer.',
  FieldPrompts_checkbox: 'Sélectionnez une ou plusieurs cases pour pouvoir continuer.',
  FieldPrompts_checkboxNOTA: 'Sélectionnez une ou plusieurs cases, ou « aucun des énoncés » pour pouvoir continuer.',
  Ordinals_1: 'premier',
  Ordinals_2: 'deuxième',
  Ordinals_3: 'troisième',
  Ordinals_4: 'quatrième',
  Ordinals_5: 'cinquième',
  Ordinals_6: 'sixième',
  Ordinals_7: 'septième',
  Ordinals_8: 'huitième',
  Ordinals_9: 'neuvième',
  Ordinals_10: 'dixième',
  Ordinals_11: 'onzième',
  Ordinals_12: 'douzième',
  Ordinals_13: 'treizième',
  RepeatAnd: 'et'
}

// Hmong
Languages.regional.hmn = {
  locale: 'hmn',
  Language: 'Hmoob',
  LanguageEN: 'Hmong',
  AskYesNo_Yes: 'Yog',
  AskYesNo_No: 'Tsis Yog',
  Close: 'Tua',
  Comment: 'Tawm lus pom',
  GoBack: 'ROV QAB',
  GoNext: 'MUS TOM NTEJ',
  LearnMore: 'Kawm Ntxiv',
  MyProgress: 'KUV LI KEV KAWM TAU NTAU PAUM CAS LAWM',
  ProvideFeedbackOrComment: 'Muab lus pom licas rau lossis tawm lus pom rau phab no',
  SaveAndExit: 'TAWM HAUV NO MUS',
  ResumeExit: 'ROV QAB UA KOM POM LOJ DUA',
  SendFeedback: 'MUS MUAB LUS POM RAU',
  SoundIsOff: 'LUB SUAB KAW LAWM',
  SoundIsOn: 'LUB SUAB QHIB LAWM',
  SoundPlay: 'Tso kom nrov suab',
  SoundStop: 'Nres',
  WhatDoYouMean: 'Koj txhais tau licas?',
  Continue: 'Ua txuas mus ntxiv',
  Exit: 'Tawm hauv no mus',
  Male: 'Tus txiv neej',
  Female: 'Tus poj niam',
  ChooseListNumber: 'Xaiv:',
  ChooseListText: 'Xaiv los ntawm cov lus uas teev tseg no:',
  CheckBoxNOTALabel: 'Tsis muaj ntawm tag nrho cov saum toj saud',
  ZoomNormal: 'Loj Me Uas Ib Txwm Muaj',
  ZoomFull: 'Qhib puv tag nrho screen',
  TextEnlarge: 'Ua kom lub npov sau ntawv loj',
  TextShrink: 'Ua kom lub npov sau ntawv me',
  TextSizeLetter: 'A',
  UploadAnswers: 'Tab tom tawm hauv no mus. Caw to...',
  CalcClear: 'Tshem tawm',
  CalcEnter: 'Nkag mus',
  MonthNamesShort: 'Lub Ib Hli Ntuj, Ob Hli Ntuj, Peb Hlis Ntuj, Plaub Hli Ntuj, Tsib Hli Ntuj, Rau Hli Ntuj, Xya Hli Ntuj, Yim Hli Ntuj, Cuaj Hli Ntuj, Kaum Hli Ntuj, Kaum Ib Hli Ntuj, Kaum Ob Hli Ntuj',
  MonthNamesLong: 'Ib Hli Ntuj, Ob Hli Ntuj, Peb Hli Ntuj, Plaub Hli Ntuj, Tsib Hli Ntuj, Rau Hli Ntuj, Xya Hli Ntuj, Yim Hli Ntuj, Cuaj Hli Ntuj, Kaum Hli Ntuj, Kaum Ib Hli Ntuj, Kaum Ob Hli Ntuj',
  FieldPrompts_ResponseRequired: 'Koj yuav tsum tau sau ib qho teb rau hauv cov kem uas khoob uas nyob txuas ntawm daim label xim liab ua ntej koj tuaj yeem ua mus ntxiv.',
  FieldPrompts_SelectionRequired: 'Koj yuav tsum tau xaiv ib qho ua ntej koj thiaj yuav tuaj yeem ua mus ntxiv tau.',
  FieldPrompts_text: 'Koj yuav tsum tau sau ib qho teb rau ntawm qhov uas zas xim uas tsis muaj ntawv ua ntej koj yuav tuaj yeem ua mus ntxiv.',
  FieldPrompts_textlong: 'koj yuav tsum tau sau ib qho teb rau ntawm qhov chaw uas zas xim ua ntej koj thiaj yuav tuaj yeem ua mus ntxiv .',
  FieldPrompts_textpick: 'Koj yuav tsum tau xaiv ib qho los ntawm qhov zas xim uas tsis muaj ntawv ua ntej koj tuaj yeem uas mus ntxiv.',
  FieldPrompts_number: 'Koj yuav tsum sau ib tug naj npawb rau ntawm qhov chaw uas zas xim ua ntej koj tuaj yeem ua mus ntxiv.',
  FieldPrompts_numberdollar: 'Koj yuav tsum sau ib co nyiaj dauslas nkag rau ntawm qhov chaws uas zas xim ua ntej koj thiaj tuaj yeem ua mus ntxiv.',
  FieldPrompts_numberssn: 'Koj yuav tsum tau ntaus ib tus naj npawb zej tsoom kev ruaj ntseg rau ntawm qhov chaw uas zas xim ua ntej koj thiaj tuaj yeem ua mus ntxiv.',
  FieldPrompts_numberphone: 'Koj yuav tsum tau ntaus tus naj npawb xov tooj rau ntawm qhov chaw uas zas xim ua ntej koj thiaj tuaj yeem ua mus ntxiv.',
  FieldPrompts_numberzip: 'Koj yuav tsum tau ntaus ib tus naj npawb zip code rau ntawm qhov chaw uas zas xim ua ntej koj tuaj yeem ua mus ntxiv.',
  FieldPrompts_numberpick: 'Koj yuav tsum tau tau xaiv ib tus naj npawb los ntawm qhov uas thas xim ua ntej koj thiaj tuaj yeem ua mus ntxiv.',
  FieldPrompts_datemdy: 'Koj yuav tsum tau sau ib lub hli, hnub thiab xyoo nkag rau ntawm qhov chaw uas thas xim ua ntej koj thiaj tuaj yeem ua mus ntxiv',
  FieldPrompts_gender: 'Koj yuav tsum tau xaiv poj niam lossis txiv neej los ntawm qhov chaw uas thas xim xaiv ua ntej koj thiaj tuaj yeem ua mus ntxiv.',
  FieldPrompts_radio: 'Koj yuav tsum tau xaiv ib qho lus teb los ntawm qhov uas thas xim xaiv ua ntej koj tuaj yeem ua mus ntxiv.',
  FieldPrompts_checkbox: 'Koj yuav tsum tau xaiv ib lossis ntau lub npov ntaus cim (checkbox) txhawm rau mus ntxiv.',
  FieldPrompts_checkboxNOTA: 'Thov caw xaiv ib lossis ntau lub npov ntaus cim (checkbox) lossis "Tsis muaj ib yam nyob saum toj saud" txhawm rau ua mus ntxiv.',
  Ordinals_1: 'thib ib',
  Ordinals_2: 'thib ob',
  Ordinals_3: 'thib peb',
  Ordinals_4: 'thib plaub',
  Ordinals_5: 'thib tsib',
  Ordinals_6: 'thib rau',
  Ordinals_7: 's thib xya',
  Ordinals_8: 'thib yim',
  Ordinals_9: 'thib cuaj',
  Ordinals_10: 'thib kaum',
  Ordinals_11: 'thib kaum ib',
  Ordinals_12: 'thib kaum ob',
  Ordinals_13: 'thib kaum peb'
}

// Korean
Languages.regional.ko = {
  locale: 'ko',
  Language: '영어',
  LanguageEN: 'Korean',
  AskYesNo_Yes: '예',
  AskYesNo_No: '아니요',
  Close: '종료',
  Comment: '의견',
  GoBack: '뒤로',
  GoNext: '다음',
  LearnMore: '자세히',
  MyProgress: '내 진행 상황',
  ProvideFeedbackOrComment: 'z',
  SaveAndExit: '나가기',
  ResumeExit: '다시 하기',
  SendFeedback: '피드백 보내기',
  SoundIsOff: '소리 끄기',
  SoundIsOn: '소리 켜기',
  SoundPlay: '재생',
  SoundStop: '정지',
  WhatDoYouMean: '어떤 의미입니까?',
  Continue: '계속',
  Exit: '나가기',
  Male: '남성',
  Female: '여성',
  ChooseListNumber: '선택:',
  ChooseListText: '이 목록에서 선택:',
  CheckBoxNOTALabel: '내용 중 해당 사항 없음',
  ZoomNormal: '정상 크기',
  ZoomFull: '전체 화면',
  TextEnlarge: '글 상자 확대',
  TextShrink: '글 상자 축소',
  TextSizeLetter: 'A',
  UploadAnswers: '나가는 중입니다. 기다려 주십시오…',
  CalcClear: '지우기',
  CalcEnter: '입력',
  MonthNamesShort: '1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월',
  MonthNamesLong: '1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월',
  FieldPrompts_ResponseRequired: '계속하기 전에 적색 라벨 옆의 공란에 응답해야 합니다.',
  FieldPrompts_SelectionRequired: '계속하기 전에 선택해야 합니다.',
  FieldPrompts_text: '계속하기 전에 강조 표시된 공간에 응답을 입력해야 합니다.',
  FieldPrompts_textlong: '계속하기 전에 강조 표시된 공간에 응답을 입력해야 합니다.',
  FieldPrompts_textpick: '계속하기 전에 강조 표시된 공간에서 선택해야 합니다.',
  FieldPrompts_number: '계속하기 전에 강조 표시된 공간에 숫자를 입력해야 합니다.',
  FieldPrompts_numberdollar: '계속하기 전에 강조 표시된 공간에 달러 액수를 입력해야 합니다.',
  FieldPrompts_numberssn: '계속하기 전에 강조 표시된 공간에 사회보장번호를 입력해야 합니다.',
  FieldPrompts_numberphone: '계속하기 전에 강조 표시된 공간에 전화번호를 입력해야 합니다.',
  FieldPrompts_numberzip: '계속하기 전에 강조 표시된 공간에 우편번호를 입력해야 합니다.',
  FieldPrompts_numberpick: '계속하기 전에 강조 표시된 공간에 숫자를 선택해야 합니다.',
  FieldPrompts_datemdy: '계속하기 전에 강조 표시된 공간에 월, 일, 연도를 입력해야 합니다.',
  FieldPrompts_gender: '계속하기 전에 강조 표시된 선택란에서 남성 또는 여성을 선택해야 합니다.',
  FieldPrompts_radio: '계속하기 전에 강조 표시된 선택란에서 응답을 선택해야 합니다.',
  FieldPrompts_checkbox: '계속하려면 1개 이상의 체크박스를 선택해야 합니다.',
  FieldPrompts_checkboxNOTA: '계속하려면 2개 이상의 체크박스를 선택하거나 "위 내용 중 해당 사항 없음"을 선택하십시오.',
  Ordinals_1: '첫째',
  Ordinals_2: '둘째',
  Ordinals_3: '셋째',
  Ordinals_4: '넷째',
  Ordinals_5: '다섯째',
  Ordinals_6: '여섯째',
  Ordinals_7: '일곱째',
  Ordinals_8: '여덟째',
  Ordinals_9: '아홉째',
  Ordinals_10: '열 번째',
  Ordinals_11: '열한 번째',
  Ordinals_12: '열두 번째',
  Ordinals_13: '열세 번째',
  RepeatAnd: '및'
}

// Mon Khmer translation
Languages.regional.mkh = {
  locale: 'mkh',
  Language: 'មន-ខ្មែរ',
  LanguageEN: 'Mon Khmer',
  AskYesNo_Yes: 'បាទ/ចាស',
  AskYesNo_No: 'ទេ',
  Close: 'បិទ',
  Comment: 'យោបល់',
  GoBack: 'ត្រលប់ក្រោយ',
  GoNext: 'បន្ទាប់',
  LearnMore: 'ស្វែងយល់បន្ថែម',
  MyProgress: 'វឌ្ឍនភាពរបស់ខ្ញុំ',
  ProvideFeedbackOrComment: 'ផ្ដល់មតិយោបល់ត្រឡប់ ឬយោបល់នៅក្នុងទំព័រនេះ',
  SaveAndExit: 'ចាកចេញ',
  ResumeExit: 'បន្ត',
  SendFeedback: 'ផ្ញើមតិស្ថាបនា',
  SoundIsOff: 'សំឡេងបិទ',
  SoundIsOn: 'សំឡេងបើក',
  SoundPlay: 'ចាក់វីដេអូ',
  SoundStop: 'បញ្ឈប់',
  WhatDoYouMean: 'តើអ្នកចង់មានន័យដូចម្ដេច?',
  Continue: 'បន្ត',
  Exit: 'ចាកចេញ',
  Male: 'ប្រុស',
  Female: 'ស្រី',
  ChooseListNumber: 'ជ្រើសរើស:',
  ChooseListText: 'ជ្រើសរើសចេញពីបញ្ជីនេះ',
  CheckBoxNOTALabel: 'គ្មានទេនៅក្នុងបញ្ជីខាងលើ',
  ZoomNormal: 'ទំហំធម្មតា',
  ZoomFull: 'ពេញអេក្រង់',
  TextEnlarge: 'ពង្រីកប្រអប់វាយអក្សរ',
  TextShrink: 'បង្រួមប្រអប់វាយអក្សរ',
  TextSizeLetter: 'A',
  UploadAnswers: 'ចាកចេញ សូមរង់ចាំ…',
  CalcClear: 'សម្អាត',
  CalcEnter: 'បញ្ចូល',
  MonthNamesShort: 'មករា, កុម្ភៈ, មីនា, មេសា, ឧសភា, មិថុនា, កក្កដា, សីហា, កញ្ញា, តុលា, វិច្ឆិកា, ធ្នូ',
  MonthNamesLong: 'មករា, កុម្ភៈ, មីនា, មេសា, ឧសភា, មិថុនា, កក្កដា, សីហា, កញ្ញា, តុលា, វិច្ឆិកា, ធ្នូ',
  FieldPrompts_ResponseRequired: 'អ្នកត្រូវតែផ្ដល់ចម្លើយនៅក្នុងប្រអប់ទទេ ដែលនៅជិតនិង អក្សរលោតក្រហម មុនពេលអ្នកអាចបន្តទៅមុខបាន។',
  FieldPrompts_SelectionRequired: 'អ្នកត្រូវតែធ្វើការជ្រើសរើសមុនពេលអ្នកអាចបន្តទៅមុខបាន។',
  FieldPrompts_text: 'អ្នកត្រូវតែវាយបញ្ចូលចម្លើយ នៅក្នុងកន្លែងដែលគូសពណ៌សម្គាល់ មុនពេលអ្នកអាចបន្តទៅមុខបាន។',
  FieldPrompts_textlong: 'អ្នកត្រូវតែវាយបញ្ចូលចម្លើយ នៅក្នុងកន្លែងដែលគូសពណ៌សម្គាល់ មុនពេលអ្នកអាចបន្តទៅមុខបាន។',
  FieldPrompts_textpick: 'អ្នកត្រូវតែធ្វើការជ្រើសរើសមុនពេលអ្នកអាចបន្តទៅមុខបាន។ ',
  FieldPrompts_number: 'អ្នកត្រូវតែជ្រើសរើសយកលេខមួយ ពីកន្លែងដែលគូសពណ៌សម្គាល់ មុនពេលអ្នកអាចបន្តទៅមុខបាន។',
  FieldPrompts_numberdollar: 'អ្នកត្រូវតែវាយបញ្ចូលចំនួនទឹកប្រាក់ជាដុល្លារ នៅកន្លែងដែលរំលេចមុនពេលអ្នកអាច បន្តបាន។',
  FieldPrompts_numberssn: 'អ្នកត្រូវតែវាយបញ្ចូលលេខកូដសន្តិសុខសង្គម នៅក្នុងកន្លែងដែលគូសពណ៌សម្គាល់ មុនពេលអ្នកអាចបន្តទៅមុខបាន។',
  FieldPrompts_numberphone: 'អ្នកត្រូវតែវាយបញ្ចូលលេខទូរសព្ទ នៅក្នុងកន្លែងដែលគូសពណ៌សម្គាល់ មុនពេលអ្នកអាចបន្តទៅមុខបាន។',
  FieldPrompts_numberzip: 'អ្នកត្រូវតែវាយបញ្ចូលលេខកូដតំបន់ នៅក្នុងកន្លែងដែលរំលេច មុន​ពេល​អ្នកអាច បន្តបាន។',
  FieldPrompts_numberpick: 'អ្នកត្រូវតែជ្រើសរើសយកលេខមួយ ពីកន្លែងដែលគូសពណ៌សម្គាល់ មុនពេលអ្នកអាចបន្តទៅមុខបាន។',
  FieldPrompts_datemdy: 'អ្នកត្រូវតែវាយបញ្ចូលខែ ថ្ងៃ និងឆ្នាំ នៅកន្លែងដែលរំលេចមុន​ពេលអ្នកអាច បន្តបាន។',
  FieldPrompts_gender: 'ជ្រើសរើសរូបមួយ ដើម្បីតំណាងឲ្យអ្នក។',
  FieldPrompts_radio: 'អ្នកត្រូវតែជ្រើសរើសចម្លើយមួយ ពីកន្លែងដែលគូសពណ៌សម្គាល់ មុនពេលអ្នកអាចបន្តទៅមុខបាន។',
  FieldPrompts_checkbox: 'អ្នកត្រូវតែជ្រើសយកប្រអប់ធីកមួយ ឬច្រើនដើម្បីបន្តទៅមុខ។ ',
  FieldPrompts_checkboxNOTA: 'អ្នកត្រូវតែជ្រើសយកប្រអប់ធីកមួយ ឬច្រើន ឬ ជ្រើសយកប្រអប់ “គ្មានប្រអប់ធីកណាមួយខាងលើ” ដើម្បីបន្តទៅមុខ។',
  Ordinals_1: 'ទីមួយ',
  Ordinals_2: 'ទីពីរ',
  Ordinals_3: 'ទីបី',
  Ordinals_4: 'ទីបួន',
  Ordinals_5: 'ទីប្រាំ',
  Ordinals_6: 'ទីប្រាំមួយ',
  Ordinals_7: 'ទីប្រាំពីរ',
  Ordinals_8: 'ទីប្រាំបី',
  Ordinals_9: 'ទីប្រាំបួន',
  Ordinals_10: 'ទីដប់',
  Ordinals_11: 'ទីដប់មួយ',
  Ordinals_12: 'ទីដប់ពីរ',
  Ordinals_13: 'ទីដប់បី',
  RepeatAnd: 'និង'
}

// Nederlands (Dutch)
Languages.regional.nl = {
  locale: 'nl',
  Language: 'Nederlands',
  LanguageEN: 'Dutch',
  AskYesNo_Yes: 'Ja',
  AskYesNo_No: 'Nee',
  Close: 'Sluiten',
  Comment: 'Commentaar',
  GoBack: 'TERUG',
  GoNext: 'VOLGENDE',
  LearnMore: 'Kom meer te weten',
  MyProgress: 'Mijn voortgang',
  ProvideFeedbackOrComment: 'Geef feedback of commentaar op deze pagina',
  SaveAndExit: 'Afronden',
  ResumeExit: 'Hervatten',
  SendFeedback: 'VERZEND FEEDBACK',
  SoundIsOff: 'GELUID IS UIT',
  SoundIsOn: 'GELUID IS AAN',
  SoundPlay: 'Afspelen',
  SoundStop: 'Stop',
  WhatDoYouMean: 'Wat bedoelt U?',
  Continue: 'Doorgaan',
  Exit: 'Uitgang',
  Male: 'Mannelijk',
  Female: 'Vrouwelijk',
  ChooseListNumber: 'Kies:',
  ChooseListText: 'Kies uit deze lijst:',
  CheckBoxNOTALabel: 'Geen van de voorgaande',
  ZoomNormal: 'Normale afmetingen',
  ZoomFull: 'Volledig scherm',
  TextEnlarge: 'Vergroot tekstvak',
  TextShrink: 'Verklein tekstvak',
  TextSizeLetter: 'A',
  UploadAnswers: 'Interessant. Even geduld alstublieft...',
  CalcClear: 'Wissen',
  CalcEnter: 'Invoeren',
  MonthNamesShort: 'Jan,Feb,Mrt,Apr,Mei,Jun,Jul,Aug,Sep,Okt,Nov,Dec',
  MonthNamesLong: 'Januari,Februari,Maart,April,Mei,Juni,Juli,Augustus,September,Oktober,November,December',
  FieldPrompts_ResponseRequired: 'Voordat U door kunt gaan moet U een antwoord invullen in het lege veld naast de rode labels.',
  FieldPrompts_SelectionRequired: 'Voordat U door kunt gaan  moet U een keuze maken.',
  FieldPrompts_text: 'Voordat U door kunt gaan moet U een antwoord typen in het gearceerde gedeelte.',
  FieldPrompts_textlong: 'Voordat U door kunt gaan moet U een antwoord typen in het gearceerde gedeelte.',
  FieldPrompts_textpick: 'Voordat U door kunt gaan moet U een keuze maken uit het gearceerde gedeelte.',
  FieldPrompts_number: 'Voordat U door kunt gaan moet U een getal typen in het gearceerde gedeelte.',
  FieldPrompts_numberdollar: 'Voordat U door kunt gaan moet U een bedrag (in dollars) typen in het gearceerde gedeelte.',
  FieldPrompts_numberssn: 'Voordat U door kunt gaan moet U een BurgerServiceNummer typen in het gearceerde gedeelte.',
  FieldPrompts_numberphone: 'Voordat U door kunt gaan moet U een telefoonnummer typen in het gearceerde gedeelte.',
  FieldPrompts_numberzip: 'Voordat U door kunt gaan moet U een postcode typen in het gearceerde gedeelte.',
  FieldPrompts_numberpick: 'Voordat U door kunt gaan moet U een getal selecteren uit het gearceerde gedeele.',
  FieldPrompts_datemdy: 'Voordat U door kunt gaan moet U een maand, dag en jaar typen in de gearceerde gedeelten.',
  FieldPrompts_gender: 'Voordat U door kunt gaan moet U ofwel man ofwel vrouw kiezen in het gearceerde gedeelte.',
  FieldPrompts_radio: 'Voordat U door kunt gaan moet U een antwoord kiezen uit het gearceerde gedeelte.',
  FieldPrompts_checkbox: 'Voordat U door kunt gaan moet U een of meer vakjes aanvinken.',
  FieldPrompts_checkboxNOTA: 'Vink alstublieft een of meerdere vakjes of het vakje "Geen van de voorgaande" aan om door te gaan.',
  Ordinals_1: 'eerste',
  Ordinals_2: 'tweede',
  Ordinals_3: 'derde',
  Ordinals_4: 'vierde',
  Ordinals_5: 'vijfde',
  Ordinals_6: 'zesde',
  Ordinals_7: 'zevende',
  Ordinals_8: 'achtste',
  Ordinals_9: 'negende',
  Ordinals_10: 'tiende',
  Ordinals_11: 'elfde',
  Ordinals_12: 'twaalfde',
  Ordinals_13: 'dertiende'
}

// Polish
Languages.regional.pl = {
  locale: 'pl',
  Language: 'Polski',
  LanguageEN: 'Polish',
  AskYesNo_Yes: 'Tak',
  AskYesNo_No: 'Nie',
  Close: 'Zamknij',
  Comment: 'Komantarz',
  GoBack: 'Powrót',
  GoNext: 'Następny',
  LearnMore: 'Zobacz więcej',
  MyProgress: 'Mój postęp',
  ProvideFeedbackOrComment: 'Zostaw opinię lub komentarz ',
  SaveAndExit: 'Wyjście',
  ResumeExit: 'Podsumowanie',
  SendFeedback: 'Wyślij podsumowanie',
  SoundIsOff: 'Dźwięk wyłączony',
  SoundIsOn: 'Dżwięk włączony',
  SoundPlay: 'Odtwarzaj',
  SoundStop: 'Stop',
  WhatDoYouMean: 'Co masz na myśli?',
  Continue: 'Dalej',
  Exit: 'Wyjście',
  Male: 'Mężczyzna',
  Female: 'Kobieta',
  ChooseListNumber: 'Wybierz',
  ChooseListText: 'Wybierz z listy',
  CheckBoxNOTALabel: 'Żadne z powyższych',
  ZoomNormal: 'Normalny rozmiar',
  ZoomFull: 'Pełen ekran',
  TextEnlarge: 'Powiększ',
  TextShrink: 'Pominiejsz',
  TextSizeLetter: 'A',
  UploadAnswers: 'Proszę czekać...',
  CalcClear: 'Wyczyść',
  CalcEnter: 'Akceptuj',
  MonthNamesShort: '1,2,3,4,5,6,7,8,9,10,11,12',
  MonthNamesLong: 'Styczeń, Luty, Marzec. Kwiecień, Maj, Cerwiec, Lipiec, Sierpień, Wrzesień, Październik, Listopad, Grudzień',
  FieldPrompts_ResponseRequired: 'Musisz najpierw wybrać odpowiedź w pustych polach obok czerwonych napisów zanim będziesz mógł kontynuować.',
  FieldPrompts_SelectionRequired: 'Musisz wybrać zanim będziesz mógł kontynuować.',
  FieldPrompts_text: 'Musisz podać odpowiedź w zaznaczonym miejscu zanim będziesz mógł kontynuować.',
  FieldPrompts_textlong: ' Musisz podać odpowiedź w zaznaczonym miejscu zanim będziesz mógł kontynuować.',
  FieldPrompts_textpick: 'Musisz wybrać zanim będziesz mógł kontynuować.',
  FieldPrompts_number: 'Musisz wpisać numer w zanaczonym polu zanim będziesz mógł kontynuować.',
  FieldPrompts_numberdollar: 'Musisz wpisać kwotę dolarów w zaznaczonym polu zanim będziesz mógł kontynuować.',
  FieldPrompts_numberssn: 'Musisz wypisać Social Security Number zanim będziesz mógł kontynuować.',
  FieldPrompts_numberphone: 'Musisz wpisać numer telefonu w zaznaczonym polu zanim będziesz mógł kontynuować.',
  FieldPrompts_numberzip: 'Musisz wpisać kod pocztowy w zaznaczonym polu zanim będziesz mógł kontynuować.',
  FieldPrompts_numberpick: 'Musisz wybrać numer z zaznaczonego pola zanim będziesz mógł kontynuować. ',
  FieldPrompts_datemdy: 'Musisz wpisać miesiąc, dzień i rok w zaznaczonym polu zanim będziesz mógł kontynuować. ',
  FieldPrompts_gender: 'Musisz wybrać płeć z zaznaczonego pola zanim będziesz mógł kontynuować.',
  FieldPrompts_radio: 'Musisz wybrać odpowiedź z zaznaczonego pola zanim będziesz mógł kontynuować.',
  FieldPrompts_checkbox: 'Musisz wybrać jedną lub kilka odpowiedzi zanim będziesz mógł kontynuować. ',
  FieldPrompts_checkboxNOTA: 'Proszę wybrać jedną lub więcej odpowiedzi albo zaznaczyć „żadne z powyższych“ aby kontynuować. ',
  Ordinals_1: 'Lierwszy',
  Ordinals_2: 'drugi',
  Ordinals_3: 'trzeci',
  Ordinals_4: 'czwarty',
  Ordinals_5: 'piąty',
  Ordinals_6: 'szósty',
  Ordinals_7: 'siódmy',
  Ordinals_8: 'ósmy',
  Ordinals_9: 'dziewiąty',
  Ordinals_10: 'dziesiąty',
  Ordinals_11: 'jedenasty',
  Ordinals_12: 'dwunasty',
  Ordinals_13: 'rzynasty'
}

// Russian
Languages.regional.ru = {
  locale: 'ru',
  LanguageEN: 'Russian',
  Language: 'Русский',
  AskYesNo_Yes: 'Да',
  AskYesNo_No: 'Нет',
  Close: 'Закрыть',
  Comment: 'Комментарии',
  GoBack: 'НАЗАД',
  GoNext: 'ДАЛЕЕ',
  LearnMore: 'Дополнительные Сведения',
  MyProgress: 'МОЙ ХОД РАБОТЫ',
  ProvideFeedbackOrComment: 'Страница для отзывов или комментариев',
  SaveAndExit: 'ВЫХОД',
  ResumeExit: 'ПРОДОЛЖЕНИЕ',
  SendFeedback: 'ОТЗЫВЫ',
  SoundIsOff: 'ЗВУК ВЫКЛЮЧЕН',
  SoundIsOn: 'ЗВУК ВКЛЮЧЕН',
  SoundPlay: 'Пуск',
  SoundStop: 'Стоп',
  WhatDoYouMean: 'Что это означает?',
  Continue: 'Продолжить ',
  Exit: 'Выйти',
  Male: 'Мужской',
  Female: 'Женский',
  ChooseListNumber: 'Выбор:',
  ChooseListText: 'Выберите из этого списка:',
  CheckBoxNOTALabel: 'Ничего из перечисленного',
  ZoomNormal: 'Обычный размер',
  ZoomFull: 'Во весь экран',
  TextEnlarge: 'Увеличить текстовое поле',
  TextShrink: 'Уменьшить текстовое поле',
  TextSizeLetter: 'A',
  UploadAnswers: 'Выход. Пожалуйста, подождите...',
  CalcClear: 'Очистка',
  CalcEnter: 'Ввод',
  MonthNamesShort: 'Янв,Фев,Март,Апр,Май,Июнъ,Июль,Авг,Сент,Окт,Нояб,Дек',
  MonthNamesLong: 'Январь,Февраль,Март,Апрель,Май,Июнь,Июль,Август,Сентябрь,Октябрь,Ноябрь,Декабрь',
  FieldPrompts_ResponseRequired: 'Поля с красной пометкой обязательные для заполнения. Введите данные перед тем, как продолжить.',
  FieldPrompts_SelectionRequired: 'Перед тем, как продолжить, необходимо сделать выбор. ',
  FieldPrompts_text: 'Перед тем, как продолжить, необходимо ответить в выделенном поле.',
  FieldPrompts_textlong: 'Перед тем, как продолжить, необходимо ответить в выделенном поле.',
  FieldPrompts_textpick: 'Перед тем, как продолжить, необходимо сделать выбор из выделенного.',
  FieldPrompts_number: 'Перед тем, как продолжить, необходимо ввести число в выделенное поле.',
  FieldPrompts_numberdollar: 'Перед тем, как продолжить, необходимо ввести сумму в долларах в выделенное поле.',
  FieldPrompts_numberssn: 'Перед тем, как продолжить, необходимо ввести номер социального страхования (Social Security Number) в выделенное поле.',
  FieldPrompts_numberphone: 'Перед тем, как продолжить, необходимо ввести номер телефона в выделенное поле.',
  FieldPrompts_numberzip: 'Перед тем, как продолжить, необходимо ввести почтовый индекс в выделенное поле.',
  FieldPrompts_numberpick: 'Перед тем, как продолжить, необходимо выбрать число из выделенного.',
  FieldPrompts_datemdy: 'Перед тем, как продолжить, необходимо ввести месяц, день, и год в выделенные поля.',
  FieldPrompts_gender: 'Перед тем, как продолжить, необходимо выбрать мужской или женский пол из выделенных вариантов.',
  FieldPrompts_radio: 'Перед тем, как продолжить, необходимо выбрать ответ из выделенных вариантов.',
  FieldPrompts_checkbox: 'Чтобы продолжить, необходимо отметить один или несколько флажков.',
  FieldPrompts_checkboxNOTA: 'Чтобы продолжить, отметьте один или несколько флажков или "Ничего из перечисленного".',
  Ordinals_1: 'первый',
  Ordinals_2: 'второй',
  Ordinals_3: 'третий',
  Ordinals_4: 'четвертый',
  Ordinals_5: 'пятый',
  Ordinals_6: 'шестой',
  Ordinals_7: 'седьмой',
  Ordinals_8: 'восьмой',
  Ordinals_9: 'девятый',
  Ordinals_10: 'десятый',
  Ordinals_11: 'одиннадцатый',
  Ordinals_12: 'двенадцатый',
  Ordinals_13: '13ый'
}

// Vietnamese language file used with A2J Viewer'
Languages.regional.vi = {
  locale: 'vi',
  Language: 'Tiếng Anh',
  LanguageEN: 'Vietnamese',
  AskYesNo_Yes: 'Có',
  AskYesNo_No: 'Không',
  Close: 'Đóng',
  Comment: 'Ý kiến/lời chú thích',
  GoBack: 'TRỞ LẠI',
  GoNext: 'TIẾP TỤC',
  LearnMore: 'Tìm hiểu thêm',
  MyProgress: 'TIẾN ĐỘ',
  ProvideFeedbackOrComment: 'Trả lời của tôi hoặc là ý kiến trong trang này',
  SaveAndExit: 'RỜI KHỎI TRANG',
  ResumeExit: 'TRỞ LẠI TRANG ĐIỀN LẦN CUỐI CÙNG',
  SendFeedback: 'GỬI CÂU TRẢ LỜI',
  SoundIsOff: 'TẮT ÂM THANH',
  SoundIsOn: 'MỞ ÂM THANH',
  SoundPlay: 'Bắt đầu',
  SoundStop: 'Ngưng',
  WhatDoYouMean: 'Quý vị có ý gì?',
  Continue: 'Tiếp tục',
  Exit: 'Rời khỏi trang',
  Male: 'Nam',
  Female: 'Nữ',
  ChooseListNumber: 'Chọn',
  ChooseListText: 'Chọn từ danh sách',
  CheckBoxNOTALabel: 'Không có câu nào được áp dụng',
  ZoomNormal: 'Chữ cỡ bình thưởng',
  ZoomFull: 'Nguyên màn hình',
  TextEnlarge: 'Làm chữ lớn hơn',
  TextShrink: 'Làm chữ nhỏ hơn',
  TextSizeLetter: 'A',
  UploadAnswers: 'Rời khỏi trang. Xin đợi một chút',
  CalcClear: 'Xóa',
  CalcEnter: 'Vào trong',
  MonthNamesShort: 'Tháng 1,Tháng 2,Tháng 3,Tháng 4,Tháng 5,Tháng 6,Tháng 7,Tháng 8,Tháng 9,Tháng 10,Tháng 11,Tháng 12',
  MonthNamesLong: 'Tháng 1,Tháng 2,Tháng 3,Tháng 4,Tháng 5,Tháng 6,Tháng 7,Tháng 8,Tháng 9,Tháng 10,Tháng 11,Tháng 12',
  FieldPrompts_ResponseRequired: 'Quý vị phải điền một câu trả lời vào ô trống ngay bên cạnh nhãn hiệu màu đỏ trước khi quý vị có thể tiếp tục.',
  FieldPrompts_SelectionRequired: 'Quý vị phải chọn một câu trả lời trước khi quý vị có thể tiếp tục.',
  FieldPrompts_text: 'Quý vị phải trả lời bằng cách đánh máy vào chỗ được tô đậm trước khi quý vị có thể tiếp tục.',
  FieldPrompts_textlong: 'Quý vị phải trả lời bằng cách đánh máy vào chỗ được tô đậm trước khi quý vị có thể tiếp tục.',
  FieldPrompts_textpick: 'Quý vị phải chọn một câu trả lời từ chỗ được tô đậm trước khi quý vị tiếp tục.',
  FieldPrompts_number: 'Quý vị phải đánh một con số vào trong chỗ được tô đậm trước khi quý vị có thể tiếp tục.',
  FieldPrompts_numberdollar: 'Quý vị phải đánh số tiền vào chỗ được tô đậm trước khi quý vị có thể được tiếp tục.',
  FieldPrompts_numberssn: 'Quý vị phải đánh số an sinh xã hội vào chỗ được tô đậm trước khi quý vị có thể tiếp tục.',
  FieldPrompts_numberphone: 'Quý vị phải đánh vào số điện thoại vào chỗ được tô đậm trước khi quý vị có thể tiếp tục. ',
  FieldPrompts_numberzip: 'Quý vị phải đánh vào số ZIP vào chỗ được tô đậm trước khi quý vị có thể tiếp tục. ',
  FieldPrompts_numberpick: 'Quý vị phải chọn một số từ chỗ được tô đậm trước khi quý vị có thể tiếp tục. ',
  FieldPrompts_datemdy: 'Xin điền tháng, ngày, và năm vào chỗ được tô đậm trước khi quý vị có thể tiếp tục. ',
  FieldPrompts_gender: 'Quý vị phải chọn nam hay nữ từ chỗ được tô đậm trước khi quý vị có thể tiếp tục. ',
  FieldPrompts_radio: 'Quý vị phải chọn một câu trả lời từ chỗ được tô đậm trước khi quý vị tiếp tục.',
  FieldPrompts_checkbox: 'Quý vị phải đánh dấu vào một ô trống hoặc nhiều hơn để tiếp tục. ',
  FieldPrompts_checkboxNOTA: 'Xin đánh dấu vào một ô trống hoặc nhiều hơn hoặc chọn "Không có câu nào áp dụng" để tiếp tục. ',
  Ordinals_1: 'Một',
  Ordinals_2: 'Hai',
  Ordinals_3: 'Ba',
  Ordinals_4: 'Bốn',
  Ordinals_5: 'Năm ',
  Ordinals_6: 'Sáu',
  Ordinals_7: 'Bảy ',
  Ordinals_8: 'Tám',
  Ordinals_9: 'Chín',
  Ordinals_10: 'Mười',
  Ordinals_11: 'Mười một',
  Ordinals_12: 'Mười hai',
  Ordinals_13: 'Mười ba',
  RepeatAnd: 'và'
}

// Simplified Chinese language file used with A2J Viewer
Languages.regional['zh-cn'] = {
  locale: 'zh-cn',
  Language: '英语',
  LanguageEN: 'Simplified Chinese',
  AskYesNo_Yes: '是',
  AskYesNo_No: '否',
  Close: '关闭',
  Comment: '评论',
  GoBack: '返回/上一页',
  GoNext: '前进/下一页',
  LearnMore: '了解更多',
  MyProgress: '我的进度',
  ProvideFeedbackOrComment: '在本页作出回应或评论',
  SaveAndExit: '退出',
  ResumeExit: '恢复',
  SendFeedback: '送出回应',
  SoundIsOff: '关闭音效',
  SoundIsOn: '打开音效',
  SoundPlay: '播放',
  SoundStop: '停止',
  WhatDoYouMean: '你的意思是？',
  Continue: '继续',
  Exit: '退出',
  Male: '男性',
  Female: '女性',
  ChooseListNumber: '选择：',
  ChooseListText: '从以下选项选择',
  CheckBoxNOTALabel: '以上皆非',
  ZoomNormal: '正常尺寸',
  ZoomFull: '全荧幕',
  TextEnlarge: '放大文字框',
  TextShrink: '缩小文字框',
  TextSizeLetter: '大',
  UploadAnswers: '退出中，请稍候…',
  CalcClear: '清除',
  CalcEnter: '输入',
  MonthNamesShort: '一月, 二月, 三月, 四月, 五月, 六月, 七月, 八月, 九月, 十月, 十一月, 十二月,',
  MonthNamesLong: '一月, 二月, 三月, 四月, 五月, 六月, 七月, 八月, 九月, 十月, 十一月, 十二月',
  FieldPrompts_ResponseRequired: '你必须先在红色标签旁的空位上作出回应才能继续下去',
  FieldPrompts_SelectionRequired: '你必须作出一项选择才能继续下去',
  FieldPrompts_text: '你必须先在黃色标记的栏位上作出回应才能继续下去',
  FieldPrompts_textlong: '你必须先在黃色标记的栏位上作出回应才能继续下去',
  FieldPrompts_textpick: '你必须先在黃色标记的栏位上作出一项选择才能继续下去',
  FieldPrompts_number: '你必须先在黃色标记的栏位上输入一个号码才能继续下去',
  FieldPrompts_numberdollar: '你必须先在黃色标记的栏位上输入一个价钱才能继续下去',
  FieldPrompts_numberssn: '你必须先在黃色标记的栏位上输入社会安全号码才能继续下去',
  FieldPrompts_numberphone: '你必须先在黃色标记的栏位上输入一个电话号码才能继续下去',
  FieldPrompts_numberzip: '你必须先在黃色标记的栏位上输入一个邮区号码才能继续下去',
  FieldPrompts_numberpick: '你必须先在黃色标记的栏位上选择一个号码才能继续下去',
  FieldPrompts_datemdy: '你必须先在黃色标记的栏位上输入月、日及年份才能继续下去',
  FieldPrompts_gender: '你必须先在黃色标记的栏位上选择男或女才能继续下去',
  FieldPrompts_radio: '你必须先在黃色标记的栏位上选择一项回应才能继续下去',
  FieldPrompts_checkbox: '你必须先在复选框里选择一项或以上才能继续下去',
  FieldPrompts_checkboxNOTA: '请在复选框选择一项或以上，或选择“以上皆非”以继续下去',
  Ordinals_1: '第一',
  Ordinals_2: '第二',
  Ordinals_3: '第三',
  Ordinals_4: '第四',
  Ordinals_5: '第五',
  Ordinals_6: '第六',
  Ordinals_7: '第七',
  Ordinals_8: '第八',
  Ordinals_9: '第九',
  Ordinals_10: '第十',
  Ordinals_11: '第十一',
  Ordinals_12: '第十二',
  Ordinals_13: '第十三',
  RepeatAnd: '和'
}

// Thai language file used with A2J Viewer
Languages.regional.th = {
  locale: 'th',
  Language: 'ไทย',
  LanguageEN: 'Thai',
  AskYesNo_Yes: 'ใช่',
  AskYesNo_No: 'ไม่',
  Close: 'ปิด',
  Comment: 'ความคิดเห็น',
  GoBack: 'ย้อนกลับ',
  GoNext: 'ถัดไป',
  LearnMore: 'เรียนรู้เพิ่มเติม',
  MyProgress: 'ความคืบหน้าของฉัน',
  ProvideFeedbackOrComment: 'แสดงคำติชมหรือความคิดเห็นในหน้านี้',
  SaveAndExit: 'ออก',
  ResumeExit: 'เริ่มใหม่',
  SendFeedback: 'ส่งคำติชม',
  SoundIsOff: 'ปิดเสียง',
  SoundIsOn: 'เปิดเสียง',
  SoundPlay: 'เล่น',
  SoundStop: 'หยุด',
  WhatDoYouMean: 'คุณหมายความว่าอย่างไร',
  Continue: 'ดำเนินการต่อ',
  Exit: 'ออก',
  Male: 'ชาย',
  Female: 'หญิง',
  ChooseListNumber: 'เลือก:',
  ChooseListText: 'เลือกจากรายการ:',
  CheckBoxNOTALabel: 'ไม่มีข้อใดข้างต้น',
  ZoomNormal: 'ขนาดปกติ',
  ZoomFull: 'เต็มหน้าจอ',
  TextEnlarge: 'ขยายกล่องข้อความ',
  TextShrink: 'ย่อกล่องข้อความ',
  TextSizeLetter: 'A',
  UploadAnswers: 'กำลังออก โปรดรอสักครู่...',
  CalcClear: 'ล้างข้อมูล',
  CalcEnter: 'ป้อน',
  MonthNamesShort: 'ม.ค,ก.พ.,มี.ค.,เม.ย.,พ.ค.,มิ.ย.,ก.ค.ส.ค.,ก.ย.,ต.ค.,พ.ย.,ธ.ค.',
  MonthNamesLong: 'มกราคม,กุมภาพันธ์,มีนาคม,เมษายน,พฤษภาคม,มิถุนายน, กรกฎาคม ,สิงหาคม,กันยายน,ตุลาคม,พฤศจิกายน,ธันวาคม',
  FieldPrompts_ResponseRequired: 'คุณต้องระบุคำตอบในช่องว่างถัดจากป้ายสีแดงก่อนจึงจะสามารถดำเนินการต่อ',
  FieldPrompts_text: 'คุณต้องพิมพ์คำตอบในช่องว่างที่ไฮไลต์ก่อนจึงจะสามารถดำเนินการต่อ',
  FieldPrompts_textlong: 'คุณต้องพิมพ์คำตอบในช่องว่างที่ไฮไลต์ก่อนจึงจะสามารถดำเนินการต่อ',
  FieldPrompts_textpick: 'คุณต้องทำการเลือกจากช่องว่างที่ไฮไลต์ก่อนจึงจะสามารถดำเนินการต่อ',
  FieldPrompts_number: 'คุณต้องพิมพ์ตัวเลขในช่องว่างที่ไฮไลต์ก่อนจึงจะสามารถดำเนินการต่อ',
  FieldPrompts_numberdollar: 'คุณต้องพิมพ์จำนวนเป็นดอลลาร์ในช่องว่างที่ไฮไลต์ก่อนจึงจะสามารถดำเนินการต่อ',
  FieldPrompts_numberssn: 'คุณต้องพิมพ์หมายเลขประกันสังคมในช่องว่างที่ไฮไลต์ก่อนจึงจะสามารถดำเนินการต่อ',
  FieldPrompts_numberphone: 'คุณต้องพิมพ์หมายเลขโทรศัพท์ในช่องว่างที่ไฮไลต์ก่อนจึงจะสามารถดำเนินการต่อ',
  FieldPrompts_numberzip: 'คุณต้องพิมพ์รหัสไปรษณีย์ในช่องว่างที่ไฮไลต์ก่อนจึงจะสามารถดำเนินการต่อ',
  FieldPrompts_numberpick: 'คุณต้องเลือกหมายเลขจากช่องว่างที่ไฮไลต์ก่อนจึงจะสามารถดำเนินการต่อ',
  FieldPrompts_datemdy: 'คุณต้องป้อนเดือน วัน และปีในช่องว่างที่ไฮไลต์ก่อนจึงจะสามารถดำเนินการต่อ',
  FieldPrompts_gender: 'คุณต้องเลือกเพศชายหรือหญิงจากช่องว่างที่ไฮไลต์ก่อนจึงจะสามารถดำเนินการต่อ',
  FieldPrompts_radio: 'คุณต้องเลือกคำตอบจากช่องว่างที่ไฮไลต์ก่อนจึงจะสามารถดำเนินการต่อ',
  FieldPrompts_checkbox: 'คุณต้องเลือกกล่องกาเครื่องหมายอย่างน้อยหนึ่งกล่องเพื่อดำเนินการต่อ',
  FieldPrompts_checkboxNOTA: 'โปรดเลือกกล่องกาเครื่องหมายอย่างน้อยหนึ่งกล่องหรือ "ไม่มีข้อใดข้างต้น" เพื่อดำเนินการต่อ',
  Ordinals_1: 'ลำดับที่หนึ่ง',
  Ordinals_2: 'ลำดับที่สอง',
  Ordinals_3: 'ลำดับที่สาม',
  Ordinals_4: 'ลำดับที่สี่',
  Ordinals_5: 'ลำดับที่ห้า',
  Ordinals_6: 'ลำดับที่หก',
  Ordinals_7: 'ลำดับที่เจ็ด',
  Ordinals_8: 'ลำดับที่แปด',
  Ordinals_9: 'ลำดับที่เก้า',
  Ordinals_10: 'ลำดับที่สิบ',
  Ordinals_11: 'ลำดับที่สิบเอ็ด',
  Ordinals_12: 'ลำดับที่สิบสอง',
  Ordinals_13: 'ลำดับที่สิบสาม',
  RepeatAnd: 'และ'
}

if ($.datepicker) {
  jQuery(function ($) {
    /* Save the English in case author switches back */
    $.datepicker.regional.en = $.datepicker.regional['']
  })

  /* Inicialización en español para la extensión 'UI date picker' para jQuery. */
  /* Traducido por Vester (xvester@gmail.com). */
  jQuery(function ($) {
    $.datepicker.regional.es = {
      closeText: 'Cerrar',
      prevText: '&#x3c;Ant',
      nextText: 'Sig&#x3e;',
      currentText: 'Hoy',
      monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
        'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
      monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun',
        'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
      dayNames: ['Domingo', 'Lunes', 'Martes', 'Mi&eacute;rcoles', 'Jueves', 'Viernes', 'S&aacute;bado'],
      dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mi&eacute;', 'Juv', 'Vie', 'S&aacute;b'],
      dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'S&aacute;'],
      weekHeader: 'Sm',
      dateFormat: 'dd/mm/yy',
      firstDay: 1,
      isRTL: false,
      showMonthAfterYear: false,
      yearSuffix: ''}
    // $.datepicker.setDefaults($.datepicker.regional['es']);
  })

  /* Vietnamese initialisation for the jQuery UI date picker plugin. */
  /* Translated by Le Thanh Huy (lthanhhuy@cit.ctu.edu.vn). */
  jQuery(function ($) {
    $.datepicker.regional.vi = {
      closeText: 'Đóng',
      prevText: '&#x3c;Trước',
      nextText: 'Tiếp&#x3e;',
      currentText: 'Hôm nay',
      monthNames: ['Tháng Một', 'Tháng Hai', 'Tháng Ba', 'Tháng Tư', 'Tháng Năm', 'Tháng Sáu',
        'Tháng Bảy', 'Tháng Tám', 'Tháng Chín', 'Tháng Mười', 'Tháng Mười Một', 'Tháng Mười Hai'],
      monthNamesShort: ['Tháng 1', 'Tháng 2', 'Tháng 3', 'Tháng 4', 'Tháng 5', 'Tháng 6',
        'Tháng 7', 'Tháng 8', 'Tháng 9', 'Tháng 10', 'Tháng 11', 'Tháng 12'],
      dayNames: ['Chủ Nhật', 'Thứ Hai', 'Thứ Ba', 'Thứ Tư', 'Thứ Năm', 'Thứ Sáu', 'Thứ Bảy'],
      dayNamesShort: ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'],
      dayNamesMin: ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'],
      weekHeader: 'Tu',
      dateFormat: 'dd/mm/yy',
      firstDay: 0,
      isRTL: false,
      showMonthAfterYear: false,
      yearSuffix: ''}
    // $.datepicker.setDefaults($.datepicker.regional['vi']);
  })

  /* Chinese initialisation for the jQuery UI date picker plugin. */
  /* Written by Cloudream (cloudream@gmail.com). */
  jQuery(function ($) {
    $.datepicker.regional['zh-cn'] = {
      closeText: '关闭',
      prevText: '&#x3c;上月',
      nextText: '下月&#x3e;',
      currentText: '今天',
      monthNames: ['一月', '二月', '三月', '四月', '五月', '六月',
        '七月', '八月', '九月', '十月', '十一月', '十二月'],
      monthNamesShort: ['一', '二', '三', '四', '五', '六',
        '七', '八', '九', '十', '十一', '十二'],
      dayNames: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
      dayNamesShort: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
      dayNamesMin: ['日', '一', '二', '三', '四', '五', '六'],
      weekHeader: '周',
      dateFormat: 'yy-mm-dd',
      firstDay: 1,
      isRTL: false,
      showMonthAfterYear: true,
      yearSuffix: '年'}
    // $.datepicker.setDefaults($.datepicker.regional['zh-CN']);
  })

  /* Korean initialisation for the jQuery calendar extension. */
  /* Written by DaeKwon Kang (ncrash.dk@gmail.com). */
  jQuery(function ($) {
    $.datepicker.regional.ko = {
      closeText: '닫기',
      prevText: '이전달',
      nextText: '다음달',
      currentText: '오늘',
      monthNames: ['1월(JAN)', '2월(FEB)', '3월(MAR)', '4월(APR)', '5월(MAY)', '6월(JUN)',
        '7월(JUL)', '8월(AUG)', '9월(SEP)', '10월(OCT)', '11월(NOV)', '12월(DEC)'],
      monthNamesShort: ['1월(JAN)', '2월(FEB)', '3월(MAR)', '4월(APR)', '5월(MAY)', '6월(JUN)',
        '7월(JUL)', '8월(AUG)', '9월(SEP)', '10월(OCT)', '11월(NOV)', '12월(DEC)'],
      dayNames: ['일', '월', '화', '수', '목', '금', '토'],
      dayNamesShort: ['일', '월', '화', '수', '목', '금', '토'],
      dayNamesMin: ['일', '월', '화', '수', '목', '금', '토'],
      weekHeader: 'Wk',
      dateFormat: 'yy-mm-dd',
      firstDay: 0,
      isRTL: false,
      showMonthAfterYear: false,
      yearSuffix: '년'}
    // $.datepicker.setDefaults($.datepicker.regional['ko']);
  })

  /* Polish initialisation for the jQuery UI date picker plugin. */
  /* Written by Jacek Wysocki (jacek.wysocki@gmail.com). */
  jQuery(function ($) {
    $.datepicker.regional.pl = {
      closeText: 'Zamknij',
      prevText: '&#x3c;Poprzedni',
      nextText: 'Następny&#x3e;',
      currentText: 'Dziś',
      monthNames: ['Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec',
        'Lipiec', 'Sierpień', 'Wrzesień', 'Październik', 'Listopad', 'Grudzień'],
      monthNamesShort: ['Sty', 'Lu', 'Mar', 'Kw', 'Maj', 'Cze',
        'Lip', 'Sie', 'Wrz', 'Pa', 'Lis', 'Gru'],
      dayNames: ['Niedziela', 'Poniedziałek', 'Wtorek', 'Środa', 'Czwartek', 'Piątek', 'Sobota'],
      dayNamesShort: ['Nie', 'Pn', 'Wt', 'Śr', 'Czw', 'Pt', 'So'],
      dayNamesMin: ['N', 'Pn', 'Wt', 'Śr', 'Cz', 'Pt', 'So'],
      weekHeader: 'Tydz',
      dateFormat: 'dd.mm.yy',
      firstDay: 1,
      isRTL: false,
      showMonthAfterYear: false,
      yearSuffix: ''}
    // $.datepicker.setDefaults($.datepicker.regional.pl);
  })

  /* Russian (UTF-8) initialisation for the jQuery UI date picker plugin. */
  /* Written by Andrew Stromnov (stromnov@gmail.com). */
  jQuery(function ($) {
    $.datepicker.regional.ru = {
      closeText: 'Закрыть',
      prevText: '&#x3c;Пред',
      nextText: 'След&#x3e;',
      currentText: 'Сегодня',
      monthNames: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь',
        'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
      monthNamesShort: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн',
        'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
      dayNames: ['воскресенье', 'понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота'],
      dayNamesShort: ['вск', 'пнд', 'втр', 'срд', 'чтв', 'птн', 'сбт'],
      dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
      weekHeader: 'Нед',
      dateFormat: 'dd.mm.yy',
      firstDay: 1,
      isRTL: false,
      showMonthAfterYear: false,
      yearSuffix: ''}
    // $.datepicker.setDefaults($.datepicker.regional.ru);
  })

  /* Dutch (UTF-8) initialisation for the jQuery UI date picker plugin. */
  /* Written by Mathias Bynens <http://mathiasbynens.be/> */
  jQuery(function ($) {
    $.datepicker.regional.nl = {
      closeText: 'Sluiten',
      prevText: '←',
      nextText: '→',
      currentText: 'Vandaag',
      monthNames: ['januari', 'februari', 'maart', 'april', 'mei', 'juni',
        'juli', 'augustus', 'september', 'oktober', 'november', 'december'],
      monthNamesShort: ['jan', 'feb', 'maa', 'apr', 'mei', 'jun',
        'jul', 'aug', 'sep', 'okt', 'nov', 'dec'],
      dayNames: ['zondag', 'maandag', 'dinsdag', 'woensdag', 'donderdag', 'vrijdag', 'zaterdag'],
      dayNamesShort: ['zon', 'maa', 'din', 'woe', 'don', 'vri', 'zat'],
      dayNamesMin: ['zo', 'ma', 'di', 'wo', 'do', 'vr', 'za'],
      weekHeader: 'Wk',
      dateFormat: 'dd/mm/yy',
      firstDay: 1,
      isRTL: false,
      showMonthAfterYear: false,
      yearSuffix: ''}
    // $.datepicker.setDefaults($.datepicker.regional.nl);
  })
}
