import 'caja/author/models/fixtures/'
import 'caja/author/models/tests/guide-test'
import 'caja/author/models/tests/a2j-node-test'
import 'caja/author/models/tests/app-state-test'
import 'caja/author/models/tests/a2j-template-test'
import 'caja/author/models/tests/a2j-variable-test'
import 'caja/author/models/tests/trace-message-test'
import 'caja/author/utils/move-item-array-test'
import 'caja/author/utils/eval-author-condition-test'

import 'caja/author/alert/alert-test'
import 'caja/author/popover/popover-test'
import 'caja/author/report/report-test'
import 'caja/author/templates/templates-test'
import 'caja/author/templates/edit/edit-test'
import 'caja/author/templates/edit/toolbar/toolbar-test'
import 'caja/author/interviews/interviews-test'
import 'caja/author/templates/list/item/item-test'
import 'caja/author/templates/list/sortbar/sortbar-test'
import 'caja/author/vertical-navbar/vertical-navbar-test'
import 'caja/author/templates/elements/varpicker/varpicker-test'
import 'caja/author/templates/elements/a2j-template/a2j-template-test'
import 'caja/author/templates/elements/a2j-variable/a2j-variable-test'
import 'caja/author/templates/elements/options-pane/options-pane-test'
import 'caja/author/templates/elements/a2j-repeat-loop/a2j-repeat-loop-test'
import 'caja/author/templates/elements/a2j-conditional/a2j-conditional-test'
import 'caja/author/templates/elements/a2j-template-ssr/a2j-template-ssr-test'
import 'caja/author/templates/elements/a2j-header-footer/a2j-header-footer-test'
import 'caja/author/templates/elements/element-container/element-container-test'

import 'caja/author/debug-panel/debug-panel-test'

import 'caja/author/pdf/assemble-test'
import 'caja/author/pdf/editor/area-test'
import 'caja/author/pdf/editor/editor-test'
import 'caja/author/pdf/checkmark-picker/checkmark-picker-test'
